package com.xuyang.mapper;

import com.xuyang.model.GoodsShopcar;
import com.xuyang.model.GoodsShopcarExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GoodsShopcarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_shopcar
     *
     * @mbg.generated
     */
    long countByExample(GoodsShopcarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_shopcar
     *
     * @mbg.generated
     */
    int deleteByExample(GoodsShopcarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_shopcar
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer carId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_shopcar
     *
     * @mbg.generated
     */
    int insert(GoodsShopcar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_shopcar
     *
     * @mbg.generated
     */
    int insertSelective(GoodsShopcar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_shopcar
     *
     * @mbg.generated
     */
    List<GoodsShopcar> selectByExample(GoodsShopcarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_shopcar
     *
     * @mbg.generated
     */
    GoodsShopcar selectByPrimaryKey(Integer carId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_shopcar
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") GoodsShopcar record, @Param("example") GoodsShopcarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_shopcar
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") GoodsShopcar record, @Param("example") GoodsShopcarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_shopcar
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GoodsShopcar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_shopcar
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GoodsShopcar record);
}