package com.xuyang.mapper;

import com.xuyang.model.Tcoupons;
import com.xuyang.model.TcouponsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TcouponsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coupons
     *
     * @mbg.generated
     */
    long countByExample(TcouponsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coupons
     *
     * @mbg.generated
     */
    int deleteByExample(TcouponsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coupons
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer couponId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coupons
     *
     * @mbg.generated
     */
    int insert(Tcoupons record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coupons
     *
     * @mbg.generated
     */
    int insertSelective(Tcoupons record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coupons
     *
     * @mbg.generated
     */
    List<Tcoupons> selectByExample(TcouponsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coupons
     *
     * @mbg.generated
     */
    Tcoupons selectByPrimaryKey(Integer couponId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coupons
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Tcoupons record, @Param("example") TcouponsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coupons
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Tcoupons record, @Param("example") TcouponsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coupons
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Tcoupons record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_coupons
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Tcoupons record);
}