package com.xuyang.mapper;

import com.xuyang.model.TgoodsAppraises;
import com.xuyang.model.TgoodsAppraisesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TgoodsAppraisesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_appraises
     *
     * @mbg.generated
     */
    long countByExample(TgoodsAppraisesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_appraises
     *
     * @mbg.generated
     */
    int deleteByExample(TgoodsAppraisesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_appraises
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer gaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_appraises
     *
     * @mbg.generated
     */
    int insert(TgoodsAppraises record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_appraises
     *
     * @mbg.generated
     */
    int insertSelective(TgoodsAppraises record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_appraises
     *
     * @mbg.generated
     */
    List<TgoodsAppraises> selectByExampleWithBLOBs(TgoodsAppraisesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_appraises
     *
     * @mbg.generated
     */
    List<TgoodsAppraises> selectByExample(TgoodsAppraisesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_appraises
     *
     * @mbg.generated
     */
    TgoodsAppraises selectByPrimaryKey(Integer gaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_appraises
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TgoodsAppraises record, @Param("example") TgoodsAppraisesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_appraises
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") TgoodsAppraises record, @Param("example") TgoodsAppraisesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_appraises
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TgoodsAppraises record, @Param("example") TgoodsAppraisesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_appraises
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TgoodsAppraises record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_appraises
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(TgoodsAppraises record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_appraises
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TgoodsAppraises record);
}