package com.xuyang.mapper;

import com.xuyang.model.TlifeAide;
import com.xuyang.model.TlifeAideExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TlifeAideMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_life_aide
     *
     * @mbg.generated
     */
    long countByExample(TlifeAideExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_life_aide
     *
     * @mbg.generated
     */
    int deleteByExample(TlifeAideExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_life_aide
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer lifeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_life_aide
     *
     * @mbg.generated
     */
    int insert(TlifeAide record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_life_aide
     *
     * @mbg.generated
     */
    int insertSelective(TlifeAide record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_life_aide
     *
     * @mbg.generated
     */
    List<TlifeAide> selectByExample(TlifeAideExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_life_aide
     *
     * @mbg.generated
     */
    TlifeAide selectByPrimaryKey(Integer lifeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_life_aide
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TlifeAide record, @Param("example") TlifeAideExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_life_aide
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TlifeAide record, @Param("example") TlifeAideExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_life_aide
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TlifeAide record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_life_aide
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TlifeAide record);
}