package com.xuyang.mapper;

import com.xuyang.model.Tmoney;
import com.xuyang.model.TmoneyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TmoneyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_money
     *
     * @mbg.generated
     */
    long countByExample(TmoneyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_money
     *
     * @mbg.generated
     */
    int deleteByExample(TmoneyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_money
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer moneyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_money
     *
     * @mbg.generated
     */
    int insert(Tmoney record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_money
     *
     * @mbg.generated
     */
    int insertSelective(Tmoney record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_money
     *
     * @mbg.generated
     */
    List<Tmoney> selectByExample(TmoneyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_money
     *
     * @mbg.generated
     */
    Tmoney selectByPrimaryKey(Integer moneyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_money
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Tmoney record, @Param("example") TmoneyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_money
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Tmoney record, @Param("example") TmoneyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_money
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Tmoney record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_money
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Tmoney record);
}