package com.xuyang.mapper;

import com.xuyang.model.TorderRefund;
import com.xuyang.model.TorderRefundExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TorderRefundMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_refund
     *
     * @mbg.generated
     */
    long countByExample(TorderRefundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_refund
     *
     * @mbg.generated
     */
    int deleteByExample(TorderRefundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_refund
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer oreId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_refund
     *
     * @mbg.generated
     */
    int insert(TorderRefund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_refund
     *
     * @mbg.generated
     */
    int insertSelective(TorderRefund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_refund
     *
     * @mbg.generated
     */
    List<TorderRefund> selectByExample(TorderRefundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_refund
     *
     * @mbg.generated
     */
    TorderRefund selectByPrimaryKey(Integer oreId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_refund
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TorderRefund record, @Param("example") TorderRefundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_refund
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TorderRefund record, @Param("example") TorderRefundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_refund
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TorderRefund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_refund
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TorderRefund record);
}