package com.xuyang.mapper;

import com.xuyang.model.TreadingTab;
import com.xuyang.model.TreadingTabExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TreadingTabMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_readingtab
     *
     * @mbg.generated
     */
    long countByExample(TreadingTabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_readingtab
     *
     * @mbg.generated
     */
    int deleteByExample(TreadingTabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_readingtab
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer clickId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_readingtab
     *
     * @mbg.generated
     */
    int insert(TreadingTab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_readingtab
     *
     * @mbg.generated
     */
    int insertSelective(TreadingTab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_readingtab
     *
     * @mbg.generated
     */
    List<TreadingTab> selectByExample(TreadingTabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_readingtab
     *
     * @mbg.generated
     */
    TreadingTab selectByPrimaryKey(Integer clickId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_readingtab
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TreadingTab record, @Param("example") TreadingTabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_readingtab
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TreadingTab record, @Param("example") TreadingTabExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_readingtab
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TreadingTab record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_readingtab
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TreadingTab record);
}