package com.xuyang.mapper;

import com.xuyang.model.Trecipient;

public interface TrecipientMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recipient
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer recipientId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recipient
     *
     * @mbg.generated
     */
    int insert(Trecipient record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recipient
     *
     * @mbg.generated
     */
    int insertSelective(Trecipient record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recipient
     *
     * @mbg.generated
     */
    Trecipient selectByPrimaryKey(Integer recipientId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recipient
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Trecipient record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_recipient
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Trecipient record);
}