package com.xuyang.model;

import java.io.Serializable;

public class Tgimage implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gimage.gimage_id
     *
     * @mbg.generated
     */
    private Integer gimageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gimage.image_parameter
     *
     * @mbg.generated
     */
    private String imageParameter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gimage.image_details
     *
     * @mbg.generated
     */
    private String imageDetails;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_gimage.g_id
     *
     * @mbg.generated
     */
    private Integer gId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_gimage
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gimage.gimage_id
     *
     * @return the value of t_gimage.gimage_id
     *
     * @mbg.generated
     */
    public Integer getGimageId() {
        return gimageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gimage.gimage_id
     *
     * @param gimageId the value for t_gimage.gimage_id
     *
     * @mbg.generated
     */
    public void setGimageId(Integer gimageId) {
        this.gimageId = gimageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gimage.image_parameter
     *
     * @return the value of t_gimage.image_parameter
     *
     * @mbg.generated
     */
    public String getImageParameter() {
        return imageParameter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gimage.image_parameter
     *
     * @param imageParameter the value for t_gimage.image_parameter
     *
     * @mbg.generated
     */
    public void setImageParameter(String imageParameter) {
        this.imageParameter = imageParameter == null ? null : imageParameter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gimage.image_details
     *
     * @return the value of t_gimage.image_details
     *
     * @mbg.generated
     */
    public String getImageDetails() {
        return imageDetails;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gimage.image_details
     *
     * @param imageDetails the value for t_gimage.image_details
     *
     * @mbg.generated
     */
    public void setImageDetails(String imageDetails) {
        this.imageDetails = imageDetails == null ? null : imageDetails.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_gimage.g_id
     *
     * @return the value of t_gimage.g_id
     *
     * @mbg.generated
     */
    public Integer getgId() {
        return gId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_gimage.g_id
     *
     * @param gId the value for t_gimage.g_id
     *
     * @mbg.generated
     */
    public void setgId(Integer gId) {
        this.gId = gId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_gimage
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", gimageId=").append(gimageId);
        sb.append(", imageParameter=").append(imageParameter);
        sb.append(", imageDetails=").append(imageDetails);
        sb.append(", gId=").append(gId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}