package com.xuyang.model;

import java.io.Serializable;
import java.util.Date;

public class TgoodsAppraises implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_appraises.ga_id
     *
     * @mbg.generated
     */
    private Integer gaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_appraises.order_id
     *
     * @mbg.generated
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_appraises.g_id
     *
     * @mbg.generated
     */
    private Integer gId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_appraises.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_appraises.g_score
     *
     * @mbg.generated
     */
    private Integer gScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_appraises.g_service_socre
     *
     * @mbg.generated
     */
    private Integer gServiceSocre;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_appraises.is_show
     *
     * @mbg.generated
     */
    private String isShow;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_appraises.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_appraises.appraises_annex
     *
     * @mbg.generated
     */
    private String appraisesAnnex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_appraises.ga_content
     *
     * @mbg.generated
     */
    private String gaContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_goods_appraises
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_appraises.ga_id
     *
     * @return the value of t_goods_appraises.ga_id
     *
     * @mbg.generated
     */
    public Integer getGaId() {
        return gaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_appraises.ga_id
     *
     * @param gaId the value for t_goods_appraises.ga_id
     *
     * @mbg.generated
     */
    public void setGaId(Integer gaId) {
        this.gaId = gaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_appraises.order_id
     *
     * @return the value of t_goods_appraises.order_id
     *
     * @mbg.generated
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_appraises.order_id
     *
     * @param orderId the value for t_goods_appraises.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_appraises.g_id
     *
     * @return the value of t_goods_appraises.g_id
     *
     * @mbg.generated
     */
    public Integer getgId() {
        return gId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_appraises.g_id
     *
     * @param gId the value for t_goods_appraises.g_id
     *
     * @mbg.generated
     */
    public void setgId(Integer gId) {
        this.gId = gId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_appraises.user_id
     *
     * @return the value of t_goods_appraises.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_appraises.user_id
     *
     * @param userId the value for t_goods_appraises.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_appraises.g_score
     *
     * @return the value of t_goods_appraises.g_score
     *
     * @mbg.generated
     */
    public Integer getgScore() {
        return gScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_appraises.g_score
     *
     * @param gScore the value for t_goods_appraises.g_score
     *
     * @mbg.generated
     */
    public void setgScore(Integer gScore) {
        this.gScore = gScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_appraises.g_service_socre
     *
     * @return the value of t_goods_appraises.g_service_socre
     *
     * @mbg.generated
     */
    public Integer getgServiceSocre() {
        return gServiceSocre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_appraises.g_service_socre
     *
     * @param gServiceSocre the value for t_goods_appraises.g_service_socre
     *
     * @mbg.generated
     */
    public void setgServiceSocre(Integer gServiceSocre) {
        this.gServiceSocre = gServiceSocre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_appraises.is_show
     *
     * @return the value of t_goods_appraises.is_show
     *
     * @mbg.generated
     */
    public String getIsShow() {
        return isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_appraises.is_show
     *
     * @param isShow the value for t_goods_appraises.is_show
     *
     * @mbg.generated
     */
    public void setIsShow(String isShow) {
        this.isShow = isShow == null ? null : isShow.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_appraises.create_time
     *
     * @return the value of t_goods_appraises.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_appraises.create_time
     *
     * @param createTime the value for t_goods_appraises.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_appraises.appraises_annex
     *
     * @return the value of t_goods_appraises.appraises_annex
     *
     * @mbg.generated
     */
    public String getAppraisesAnnex() {
        return appraisesAnnex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_appraises.appraises_annex
     *
     * @param appraisesAnnex the value for t_goods_appraises.appraises_annex
     *
     * @mbg.generated
     */
    public void setAppraisesAnnex(String appraisesAnnex) {
        this.appraisesAnnex = appraisesAnnex == null ? null : appraisesAnnex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_appraises.ga_content
     *
     * @return the value of t_goods_appraises.ga_content
     *
     * @mbg.generated
     */
    public String getGaContent() {
        return gaContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_appraises.ga_content
     *
     * @param gaContent the value for t_goods_appraises.ga_content
     *
     * @mbg.generated
     */
    public void setGaContent(String gaContent) {
        this.gaContent = gaContent == null ? null : gaContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_appraises
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", gaId=").append(gaId);
        sb.append(", orderId=").append(orderId);
        sb.append(", gId=").append(gId);
        sb.append(", userId=").append(userId);
        sb.append(", gScore=").append(gScore);
        sb.append(", gServiceSocre=").append(gServiceSocre);
        sb.append(", isShow=").append(isShow);
        sb.append(", createTime=").append(createTime);
        sb.append(", appraisesAnnex=").append(appraisesAnnex);
        sb.append(", gaContent=").append(gaContent);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}