package com.xuyang.model;

import java.util.ArrayList;
import java.util.List;

public class TgoodsImageExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_goods_image
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_goods_image
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_goods_image
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_image
     *
     * @mbg.generated
     */
    public TgoodsImageExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_image
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_image
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_image
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_image
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_image
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_image
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_image
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_image
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_image
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_image
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_goods_image
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andGiIdIsNull() {
            addCriterion("gi_id is null");
            return (Criteria) this;
        }

        public Criteria andGiIdIsNotNull() {
            addCriterion("gi_id is not null");
            return (Criteria) this;
        }

        public Criteria andGiIdEqualTo(Integer value) {
            addCriterion("gi_id =", value, "giId");
            return (Criteria) this;
        }

        public Criteria andGiIdNotEqualTo(Integer value) {
            addCriterion("gi_id <>", value, "giId");
            return (Criteria) this;
        }

        public Criteria andGiIdGreaterThan(Integer value) {
            addCriterion("gi_id >", value, "giId");
            return (Criteria) this;
        }

        public Criteria andGiIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("gi_id >=", value, "giId");
            return (Criteria) this;
        }

        public Criteria andGiIdLessThan(Integer value) {
            addCriterion("gi_id <", value, "giId");
            return (Criteria) this;
        }

        public Criteria andGiIdLessThanOrEqualTo(Integer value) {
            addCriterion("gi_id <=", value, "giId");
            return (Criteria) this;
        }

        public Criteria andGiIdIn(List<Integer> values) {
            addCriterion("gi_id in", values, "giId");
            return (Criteria) this;
        }

        public Criteria andGiIdNotIn(List<Integer> values) {
            addCriterion("gi_id not in", values, "giId");
            return (Criteria) this;
        }

        public Criteria andGiIdBetween(Integer value1, Integer value2) {
            addCriterion("gi_id between", value1, value2, "giId");
            return (Criteria) this;
        }

        public Criteria andGiIdNotBetween(Integer value1, Integer value2) {
            addCriterion("gi_id not between", value1, value2, "giId");
            return (Criteria) this;
        }

        public Criteria andGiImageIsNull() {
            addCriterion("gi_image is null");
            return (Criteria) this;
        }

        public Criteria andGiImageIsNotNull() {
            addCriterion("gi_image is not null");
            return (Criteria) this;
        }

        public Criteria andGiImageEqualTo(String value) {
            addCriterion("gi_image =", value, "giImage");
            return (Criteria) this;
        }

        public Criteria andGiImageNotEqualTo(String value) {
            addCriterion("gi_image <>", value, "giImage");
            return (Criteria) this;
        }

        public Criteria andGiImageGreaterThan(String value) {
            addCriterion("gi_image >", value, "giImage");
            return (Criteria) this;
        }

        public Criteria andGiImageGreaterThanOrEqualTo(String value) {
            addCriterion("gi_image >=", value, "giImage");
            return (Criteria) this;
        }

        public Criteria andGiImageLessThan(String value) {
            addCriterion("gi_image <", value, "giImage");
            return (Criteria) this;
        }

        public Criteria andGiImageLessThanOrEqualTo(String value) {
            addCriterion("gi_image <=", value, "giImage");
            return (Criteria) this;
        }

        public Criteria andGiImageLike(String value) {
            addCriterion("gi_image like", value, "giImage");
            return (Criteria) this;
        }

        public Criteria andGiImageNotLike(String value) {
            addCriterion("gi_image not like", value, "giImage");
            return (Criteria) this;
        }

        public Criteria andGiImageIn(List<String> values) {
            addCriterion("gi_image in", values, "giImage");
            return (Criteria) this;
        }

        public Criteria andGiImageNotIn(List<String> values) {
            addCriterion("gi_image not in", values, "giImage");
            return (Criteria) this;
        }

        public Criteria andGiImageBetween(String value1, String value2) {
            addCriterion("gi_image between", value1, value2, "giImage");
            return (Criteria) this;
        }

        public Criteria andGiImageNotBetween(String value1, String value2) {
            addCriterion("gi_image not between", value1, value2, "giImage");
            return (Criteria) this;
        }

        public Criteria andGiThumbsIsNull() {
            addCriterion("gi_thumbs is null");
            return (Criteria) this;
        }

        public Criteria andGiThumbsIsNotNull() {
            addCriterion("gi_thumbs is not null");
            return (Criteria) this;
        }

        public Criteria andGiThumbsEqualTo(String value) {
            addCriterion("gi_thumbs =", value, "giThumbs");
            return (Criteria) this;
        }

        public Criteria andGiThumbsNotEqualTo(String value) {
            addCriterion("gi_thumbs <>", value, "giThumbs");
            return (Criteria) this;
        }

        public Criteria andGiThumbsGreaterThan(String value) {
            addCriterion("gi_thumbs >", value, "giThumbs");
            return (Criteria) this;
        }

        public Criteria andGiThumbsGreaterThanOrEqualTo(String value) {
            addCriterion("gi_thumbs >=", value, "giThumbs");
            return (Criteria) this;
        }

        public Criteria andGiThumbsLessThan(String value) {
            addCriterion("gi_thumbs <", value, "giThumbs");
            return (Criteria) this;
        }

        public Criteria andGiThumbsLessThanOrEqualTo(String value) {
            addCriterion("gi_thumbs <=", value, "giThumbs");
            return (Criteria) this;
        }

        public Criteria andGiThumbsLike(String value) {
            addCriterion("gi_thumbs like", value, "giThumbs");
            return (Criteria) this;
        }

        public Criteria andGiThumbsNotLike(String value) {
            addCriterion("gi_thumbs not like", value, "giThumbs");
            return (Criteria) this;
        }

        public Criteria andGiThumbsIn(List<String> values) {
            addCriterion("gi_thumbs in", values, "giThumbs");
            return (Criteria) this;
        }

        public Criteria andGiThumbsNotIn(List<String> values) {
            addCriterion("gi_thumbs not in", values, "giThumbs");
            return (Criteria) this;
        }

        public Criteria andGiThumbsBetween(String value1, String value2) {
            addCriterion("gi_thumbs between", value1, value2, "giThumbs");
            return (Criteria) this;
        }

        public Criteria andGiThumbsNotBetween(String value1, String value2) {
            addCriterion("gi_thumbs not between", value1, value2, "giThumbs");
            return (Criteria) this;
        }

        public Criteria andGIdIsNull() {
            addCriterion("g_id is null");
            return (Criteria) this;
        }

        public Criteria andGIdIsNotNull() {
            addCriterion("g_id is not null");
            return (Criteria) this;
        }

        public Criteria andGIdEqualTo(Integer value) {
            addCriterion("g_id =", value, "gId");
            return (Criteria) this;
        }

        public Criteria andGIdNotEqualTo(Integer value) {
            addCriterion("g_id <>", value, "gId");
            return (Criteria) this;
        }

        public Criteria andGIdGreaterThan(Integer value) {
            addCriterion("g_id >", value, "gId");
            return (Criteria) this;
        }

        public Criteria andGIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("g_id >=", value, "gId");
            return (Criteria) this;
        }

        public Criteria andGIdLessThan(Integer value) {
            addCriterion("g_id <", value, "gId");
            return (Criteria) this;
        }

        public Criteria andGIdLessThanOrEqualTo(Integer value) {
            addCriterion("g_id <=", value, "gId");
            return (Criteria) this;
        }

        public Criteria andGIdIn(List<Integer> values) {
            addCriterion("g_id in", values, "gId");
            return (Criteria) this;
        }

        public Criteria andGIdNotIn(List<Integer> values) {
            addCriterion("g_id not in", values, "gId");
            return (Criteria) this;
        }

        public Criteria andGIdBetween(Integer value1, Integer value2) {
            addCriterion("g_id between", value1, value2, "gId");
            return (Criteria) this;
        }

        public Criteria andGIdNotBetween(Integer value1, Integer value2) {
            addCriterion("g_id not between", value1, value2, "gId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_goods_image
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_goods_image
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}