package com.xuyang.model;

import java.io.Serializable;

public class TgoodsSpecs implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_specs.format_id
     *
     * @mbg.generated
     */
    private Integer formatId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_specs.format_name
     *
     * @mbg.generated
     */
    private String formatName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_specs.format_status
     *
     * @mbg.generated
     */
    private Integer formatStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_goods_specs
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_specs.format_id
     *
     * @return the value of t_goods_specs.format_id
     *
     * @mbg.generated
     */
    public Integer getFormatId() {
        return formatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_specs.format_id
     *
     * @param formatId the value for t_goods_specs.format_id
     *
     * @mbg.generated
     */
    public void setFormatId(Integer formatId) {
        this.formatId = formatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_specs.format_name
     *
     * @return the value of t_goods_specs.format_name
     *
     * @mbg.generated
     */
    public String getFormatName() {
        return formatName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_specs.format_name
     *
     * @param formatName the value for t_goods_specs.format_name
     *
     * @mbg.generated
     */
    public void setFormatName(String formatName) {
        this.formatName = formatName == null ? null : formatName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_specs.format_status
     *
     * @return the value of t_goods_specs.format_status
     *
     * @mbg.generated
     */
    public Integer getFormatStatus() {
        return formatStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_specs.format_status
     *
     * @param formatStatus the value for t_goods_specs.format_status
     *
     * @mbg.generated
     */
    public void setFormatStatus(Integer formatStatus) {
        this.formatStatus = formatStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_specs
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", formatId=").append(formatId);
        sb.append(", formatName=").append(formatName);
        sb.append(", formatStatus=").append(formatStatus);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}