package com.xuyang.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ThouseExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_house
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_house
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_house
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_house
     *
     * @mbg.generated
     */
    public ThouseExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_house
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_house
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_house
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_house
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_house
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_house
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_house
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_house
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_house
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_house
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_house
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andHouseIdIsNull() {
            addCriterion("house_id is null");
            return (Criteria) this;
        }

        public Criteria andHouseIdIsNotNull() {
            addCriterion("house_id is not null");
            return (Criteria) this;
        }

        public Criteria andHouseIdEqualTo(Integer value) {
            addCriterion("house_id =", value, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdNotEqualTo(Integer value) {
            addCriterion("house_id <>", value, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdGreaterThan(Integer value) {
            addCriterion("house_id >", value, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("house_id >=", value, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdLessThan(Integer value) {
            addCriterion("house_id <", value, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdLessThanOrEqualTo(Integer value) {
            addCriterion("house_id <=", value, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdIn(List<Integer> values) {
            addCriterion("house_id in", values, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdNotIn(List<Integer> values) {
            addCriterion("house_id not in", values, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdBetween(Integer value1, Integer value2) {
            addCriterion("house_id between", value1, value2, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseIdNotBetween(Integer value1, Integer value2) {
            addCriterion("house_id not between", value1, value2, "houseId");
            return (Criteria) this;
        }

        public Criteria andHouseTimeIsNull() {
            addCriterion("house_time is null");
            return (Criteria) this;
        }

        public Criteria andHouseTimeIsNotNull() {
            addCriterion("house_time is not null");
            return (Criteria) this;
        }

        public Criteria andHouseTimeEqualTo(Date value) {
            addCriterion("house_time =", value, "houseTime");
            return (Criteria) this;
        }

        public Criteria andHouseTimeNotEqualTo(Date value) {
            addCriterion("house_time <>", value, "houseTime");
            return (Criteria) this;
        }

        public Criteria andHouseTimeGreaterThan(Date value) {
            addCriterion("house_time >", value, "houseTime");
            return (Criteria) this;
        }

        public Criteria andHouseTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("house_time >=", value, "houseTime");
            return (Criteria) this;
        }

        public Criteria andHouseTimeLessThan(Date value) {
            addCriterion("house_time <", value, "houseTime");
            return (Criteria) this;
        }

        public Criteria andHouseTimeLessThanOrEqualTo(Date value) {
            addCriterion("house_time <=", value, "houseTime");
            return (Criteria) this;
        }

        public Criteria andHouseTimeIn(List<Date> values) {
            addCriterion("house_time in", values, "houseTime");
            return (Criteria) this;
        }

        public Criteria andHouseTimeNotIn(List<Date> values) {
            addCriterion("house_time not in", values, "houseTime");
            return (Criteria) this;
        }

        public Criteria andHouseTimeBetween(Date value1, Date value2) {
            addCriterion("house_time between", value1, value2, "houseTime");
            return (Criteria) this;
        }

        public Criteria andHouseTimeNotBetween(Date value1, Date value2) {
            addCriterion("house_time not between", value1, value2, "houseTime");
            return (Criteria) this;
        }

        public Criteria andGIdIsNull() {
            addCriterion("g_id is null");
            return (Criteria) this;
        }

        public Criteria andGIdIsNotNull() {
            addCriterion("g_id is not null");
            return (Criteria) this;
        }

        public Criteria andGIdEqualTo(Integer value) {
            addCriterion("g_id =", value, "gId");
            return (Criteria) this;
        }

        public Criteria andGIdNotEqualTo(Integer value) {
            addCriterion("g_id <>", value, "gId");
            return (Criteria) this;
        }

        public Criteria andGIdGreaterThan(Integer value) {
            addCriterion("g_id >", value, "gId");
            return (Criteria) this;
        }

        public Criteria andGIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("g_id >=", value, "gId");
            return (Criteria) this;
        }

        public Criteria andGIdLessThan(Integer value) {
            addCriterion("g_id <", value, "gId");
            return (Criteria) this;
        }

        public Criteria andGIdLessThanOrEqualTo(Integer value) {
            addCriterion("g_id <=", value, "gId");
            return (Criteria) this;
        }

        public Criteria andGIdIn(List<Integer> values) {
            addCriterion("g_id in", values, "gId");
            return (Criteria) this;
        }

        public Criteria andGIdNotIn(List<Integer> values) {
            addCriterion("g_id not in", values, "gId");
            return (Criteria) this;
        }

        public Criteria andGIdBetween(Integer value1, Integer value2) {
            addCriterion("g_id between", value1, value2, "gId");
            return (Criteria) this;
        }

        public Criteria andGIdNotBetween(Integer value1, Integer value2) {
            addCriterion("g_id not between", value1, value2, "gId");
            return (Criteria) this;
        }

        public Criteria andDyIdIsNull() {
            addCriterion("dy_id is null");
            return (Criteria) this;
        }

        public Criteria andDyIdIsNotNull() {
            addCriterion("dy_id is not null");
            return (Criteria) this;
        }

        public Criteria andDyIdEqualTo(Integer value) {
            addCriterion("dy_id =", value, "dyId");
            return (Criteria) this;
        }

        public Criteria andDyIdNotEqualTo(Integer value) {
            addCriterion("dy_id <>", value, "dyId");
            return (Criteria) this;
        }

        public Criteria andDyIdGreaterThan(Integer value) {
            addCriterion("dy_id >", value, "dyId");
            return (Criteria) this;
        }

        public Criteria andDyIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("dy_id >=", value, "dyId");
            return (Criteria) this;
        }

        public Criteria andDyIdLessThan(Integer value) {
            addCriterion("dy_id <", value, "dyId");
            return (Criteria) this;
        }

        public Criteria andDyIdLessThanOrEqualTo(Integer value) {
            addCriterion("dy_id <=", value, "dyId");
            return (Criteria) this;
        }

        public Criteria andDyIdIn(List<Integer> values) {
            addCriterion("dy_id in", values, "dyId");
            return (Criteria) this;
        }

        public Criteria andDyIdNotIn(List<Integer> values) {
            addCriterion("dy_id not in", values, "dyId");
            return (Criteria) this;
        }

        public Criteria andDyIdBetween(Integer value1, Integer value2) {
            addCriterion("dy_id between", value1, value2, "dyId");
            return (Criteria) this;
        }

        public Criteria andDyIdNotBetween(Integer value1, Integer value2) {
            addCriterion("dy_id not between", value1, value2, "dyId");
            return (Criteria) this;
        }

        public Criteria andGNameIsNull() {
            addCriterion("g_name is null");
            return (Criteria) this;
        }

        public Criteria andGNameIsNotNull() {
            addCriterion("g_name is not null");
            return (Criteria) this;
        }

        public Criteria andGNameEqualTo(String value) {
            addCriterion("g_name =", value, "gName");
            return (Criteria) this;
        }

        public Criteria andGNameNotEqualTo(String value) {
            addCriterion("g_name <>", value, "gName");
            return (Criteria) this;
        }

        public Criteria andGNameGreaterThan(String value) {
            addCriterion("g_name >", value, "gName");
            return (Criteria) this;
        }

        public Criteria andGNameGreaterThanOrEqualTo(String value) {
            addCriterion("g_name >=", value, "gName");
            return (Criteria) this;
        }

        public Criteria andGNameLessThan(String value) {
            addCriterion("g_name <", value, "gName");
            return (Criteria) this;
        }

        public Criteria andGNameLessThanOrEqualTo(String value) {
            addCriterion("g_name <=", value, "gName");
            return (Criteria) this;
        }

        public Criteria andGNameLike(String value) {
            addCriterion("g_name like", value, "gName");
            return (Criteria) this;
        }

        public Criteria andGNameNotLike(String value) {
            addCriterion("g_name not like", value, "gName");
            return (Criteria) this;
        }

        public Criteria andGNameIn(List<String> values) {
            addCriterion("g_name in", values, "gName");
            return (Criteria) this;
        }

        public Criteria andGNameNotIn(List<String> values) {
            addCriterion("g_name not in", values, "gName");
            return (Criteria) this;
        }

        public Criteria andGNameBetween(String value1, String value2) {
            addCriterion("g_name between", value1, value2, "gName");
            return (Criteria) this;
        }

        public Criteria andGNameNotBetween(String value1, String value2) {
            addCriterion("g_name not between", value1, value2, "gName");
            return (Criteria) this;
        }

        public Criteria andDyTitleIsNull() {
            addCriterion("dy_title is null");
            return (Criteria) this;
        }

        public Criteria andDyTitleIsNotNull() {
            addCriterion("dy_title is not null");
            return (Criteria) this;
        }

        public Criteria andDyTitleEqualTo(String value) {
            addCriterion("dy_title =", value, "dyTitle");
            return (Criteria) this;
        }

        public Criteria andDyTitleNotEqualTo(String value) {
            addCriterion("dy_title <>", value, "dyTitle");
            return (Criteria) this;
        }

        public Criteria andDyTitleGreaterThan(String value) {
            addCriterion("dy_title >", value, "dyTitle");
            return (Criteria) this;
        }

        public Criteria andDyTitleGreaterThanOrEqualTo(String value) {
            addCriterion("dy_title >=", value, "dyTitle");
            return (Criteria) this;
        }

        public Criteria andDyTitleLessThan(String value) {
            addCriterion("dy_title <", value, "dyTitle");
            return (Criteria) this;
        }

        public Criteria andDyTitleLessThanOrEqualTo(String value) {
            addCriterion("dy_title <=", value, "dyTitle");
            return (Criteria) this;
        }

        public Criteria andDyTitleLike(String value) {
            addCriterion("dy_title like", value, "dyTitle");
            return (Criteria) this;
        }

        public Criteria andDyTitleNotLike(String value) {
            addCriterion("dy_title not like", value, "dyTitle");
            return (Criteria) this;
        }

        public Criteria andDyTitleIn(List<String> values) {
            addCriterion("dy_title in", values, "dyTitle");
            return (Criteria) this;
        }

        public Criteria andDyTitleNotIn(List<String> values) {
            addCriterion("dy_title not in", values, "dyTitle");
            return (Criteria) this;
        }

        public Criteria andDyTitleBetween(String value1, String value2) {
            addCriterion("dy_title between", value1, value2, "dyTitle");
            return (Criteria) this;
        }

        public Criteria andDyTitleNotBetween(String value1, String value2) {
            addCriterion("dy_title not between", value1, value2, "dyTitle");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_house
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_house
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}