package com.xuyang.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class TorderGoodsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_order_goods
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_order_goods
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_order_goods
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_goods
     *
     * @mbg.generated
     */
    public TorderGoodsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_goods
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_goods
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_goods
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_goods
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_goods
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_goods
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_goods
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_goods
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_goods
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_goods
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_order_goods
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOgIdIsNull() {
            addCriterion("og_id is null");
            return (Criteria) this;
        }

        public Criteria andOgIdIsNotNull() {
            addCriterion("og_id is not null");
            return (Criteria) this;
        }

        public Criteria andOgIdEqualTo(Integer value) {
            addCriterion("og_id =", value, "ogId");
            return (Criteria) this;
        }

        public Criteria andOgIdNotEqualTo(Integer value) {
            addCriterion("og_id <>", value, "ogId");
            return (Criteria) this;
        }

        public Criteria andOgIdGreaterThan(Integer value) {
            addCriterion("og_id >", value, "ogId");
            return (Criteria) this;
        }

        public Criteria andOgIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("og_id >=", value, "ogId");
            return (Criteria) this;
        }

        public Criteria andOgIdLessThan(Integer value) {
            addCriterion("og_id <", value, "ogId");
            return (Criteria) this;
        }

        public Criteria andOgIdLessThanOrEqualTo(Integer value) {
            addCriterion("og_id <=", value, "ogId");
            return (Criteria) this;
        }

        public Criteria andOgIdIn(List<Integer> values) {
            addCriterion("og_id in", values, "ogId");
            return (Criteria) this;
        }

        public Criteria andOgIdNotIn(List<Integer> values) {
            addCriterion("og_id not in", values, "ogId");
            return (Criteria) this;
        }

        public Criteria andOgIdBetween(Integer value1, Integer value2) {
            addCriterion("og_id between", value1, value2, "ogId");
            return (Criteria) this;
        }

        public Criteria andOgIdNotBetween(Integer value1, Integer value2) {
            addCriterion("og_id not between", value1, value2, "ogId");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNull() {
            addCriterion("order_id is null");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNotNull() {
            addCriterion("order_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderIdEqualTo(Integer value) {
            addCriterion("order_id =", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotEqualTo(Integer value) {
            addCriterion("order_id <>", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThan(Integer value) {
            addCriterion("order_id >", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("order_id >=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThan(Integer value) {
            addCriterion("order_id <", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThanOrEqualTo(Integer value) {
            addCriterion("order_id <=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdIn(List<Integer> values) {
            addCriterion("order_id in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotIn(List<Integer> values) {
            addCriterion("order_id not in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdBetween(Integer value1, Integer value2) {
            addCriterion("order_id between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotBetween(Integer value1, Integer value2) {
            addCriterion("order_id not between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andGIdIsNull() {
            addCriterion("g_id is null");
            return (Criteria) this;
        }

        public Criteria andGIdIsNotNull() {
            addCriterion("g_id is not null");
            return (Criteria) this;
        }

        public Criteria andGIdEqualTo(Integer value) {
            addCriterion("g_id =", value, "gId");
            return (Criteria) this;
        }

        public Criteria andGIdNotEqualTo(Integer value) {
            addCriterion("g_id <>", value, "gId");
            return (Criteria) this;
        }

        public Criteria andGIdGreaterThan(Integer value) {
            addCriterion("g_id >", value, "gId");
            return (Criteria) this;
        }

        public Criteria andGIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("g_id >=", value, "gId");
            return (Criteria) this;
        }

        public Criteria andGIdLessThan(Integer value) {
            addCriterion("g_id <", value, "gId");
            return (Criteria) this;
        }

        public Criteria andGIdLessThanOrEqualTo(Integer value) {
            addCriterion("g_id <=", value, "gId");
            return (Criteria) this;
        }

        public Criteria andGIdIn(List<Integer> values) {
            addCriterion("g_id in", values, "gId");
            return (Criteria) this;
        }

        public Criteria andGIdNotIn(List<Integer> values) {
            addCriterion("g_id not in", values, "gId");
            return (Criteria) this;
        }

        public Criteria andGIdBetween(Integer value1, Integer value2) {
            addCriterion("g_id between", value1, value2, "gId");
            return (Criteria) this;
        }

        public Criteria andGIdNotBetween(Integer value1, Integer value2) {
            addCriterion("g_id not between", value1, value2, "gId");
            return (Criteria) this;
        }

        public Criteria andGoodsNumsIsNull() {
            addCriterion("goods_nums is null");
            return (Criteria) this;
        }

        public Criteria andGoodsNumsIsNotNull() {
            addCriterion("goods_nums is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsNumsEqualTo(Integer value) {
            addCriterion("goods_nums =", value, "goodsNums");
            return (Criteria) this;
        }

        public Criteria andGoodsNumsNotEqualTo(Integer value) {
            addCriterion("goods_nums <>", value, "goodsNums");
            return (Criteria) this;
        }

        public Criteria andGoodsNumsGreaterThan(Integer value) {
            addCriterion("goods_nums >", value, "goodsNums");
            return (Criteria) this;
        }

        public Criteria andGoodsNumsGreaterThanOrEqualTo(Integer value) {
            addCriterion("goods_nums >=", value, "goodsNums");
            return (Criteria) this;
        }

        public Criteria andGoodsNumsLessThan(Integer value) {
            addCriterion("goods_nums <", value, "goodsNums");
            return (Criteria) this;
        }

        public Criteria andGoodsNumsLessThanOrEqualTo(Integer value) {
            addCriterion("goods_nums <=", value, "goodsNums");
            return (Criteria) this;
        }

        public Criteria andGoodsNumsIn(List<Integer> values) {
            addCriterion("goods_nums in", values, "goodsNums");
            return (Criteria) this;
        }

        public Criteria andGoodsNumsNotIn(List<Integer> values) {
            addCriterion("goods_nums not in", values, "goodsNums");
            return (Criteria) this;
        }

        public Criteria andGoodsNumsBetween(Integer value1, Integer value2) {
            addCriterion("goods_nums between", value1, value2, "goodsNums");
            return (Criteria) this;
        }

        public Criteria andGoodsNumsNotBetween(Integer value1, Integer value2) {
            addCriterion("goods_nums not between", value1, value2, "goodsNums");
            return (Criteria) this;
        }

        public Criteria andGoodsPriceIsNull() {
            addCriterion("goods_price is null");
            return (Criteria) this;
        }

        public Criteria andGoodsPriceIsNotNull() {
            addCriterion("goods_price is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsPriceEqualTo(BigDecimal value) {
            addCriterion("goods_price =", value, "goodsPrice");
            return (Criteria) this;
        }

        public Criteria andGoodsPriceNotEqualTo(BigDecimal value) {
            addCriterion("goods_price <>", value, "goodsPrice");
            return (Criteria) this;
        }

        public Criteria andGoodsPriceGreaterThan(BigDecimal value) {
            addCriterion("goods_price >", value, "goodsPrice");
            return (Criteria) this;
        }

        public Criteria andGoodsPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("goods_price >=", value, "goodsPrice");
            return (Criteria) this;
        }

        public Criteria andGoodsPriceLessThan(BigDecimal value) {
            addCriterion("goods_price <", value, "goodsPrice");
            return (Criteria) this;
        }

        public Criteria andGoodsPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("goods_price <=", value, "goodsPrice");
            return (Criteria) this;
        }

        public Criteria andGoodsPriceIn(List<BigDecimal> values) {
            addCriterion("goods_price in", values, "goodsPrice");
            return (Criteria) this;
        }

        public Criteria andGoodsPriceNotIn(List<BigDecimal> values) {
            addCriterion("goods_price not in", values, "goodsPrice");
            return (Criteria) this;
        }

        public Criteria andGoodsPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("goods_price between", value1, value2, "goodsPrice");
            return (Criteria) this;
        }

        public Criteria andGoodsPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("goods_price not between", value1, value2, "goodsPrice");
            return (Criteria) this;
        }

        public Criteria andGtIdIsNull() {
            addCriterion("gt_id is null");
            return (Criteria) this;
        }

        public Criteria andGtIdIsNotNull() {
            addCriterion("gt_id is not null");
            return (Criteria) this;
        }

        public Criteria andGtIdEqualTo(Integer value) {
            addCriterion("gt_id =", value, "gtId");
            return (Criteria) this;
        }

        public Criteria andGtIdNotEqualTo(Integer value) {
            addCriterion("gt_id <>", value, "gtId");
            return (Criteria) this;
        }

        public Criteria andGtIdGreaterThan(Integer value) {
            addCriterion("gt_id >", value, "gtId");
            return (Criteria) this;
        }

        public Criteria andGtIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("gt_id >=", value, "gtId");
            return (Criteria) this;
        }

        public Criteria andGtIdLessThan(Integer value) {
            addCriterion("gt_id <", value, "gtId");
            return (Criteria) this;
        }

        public Criteria andGtIdLessThanOrEqualTo(Integer value) {
            addCriterion("gt_id <=", value, "gtId");
            return (Criteria) this;
        }

        public Criteria andGtIdIn(List<Integer> values) {
            addCriterion("gt_id in", values, "gtId");
            return (Criteria) this;
        }

        public Criteria andGtIdNotIn(List<Integer> values) {
            addCriterion("gt_id not in", values, "gtId");
            return (Criteria) this;
        }

        public Criteria andGtIdBetween(Integer value1, Integer value2) {
            addCriterion("gt_id between", value1, value2, "gtId");
            return (Criteria) this;
        }

        public Criteria andGtIdNotBetween(Integer value1, Integer value2) {
            addCriterion("gt_id not between", value1, value2, "gtId");
            return (Criteria) this;
        }

        public Criteria andGtNameIsNull() {
            addCriterion("gt_name is null");
            return (Criteria) this;
        }

        public Criteria andGtNameIsNotNull() {
            addCriterion("gt_name is not null");
            return (Criteria) this;
        }

        public Criteria andGtNameEqualTo(String value) {
            addCriterion("gt_name =", value, "gtName");
            return (Criteria) this;
        }

        public Criteria andGtNameNotEqualTo(String value) {
            addCriterion("gt_name <>", value, "gtName");
            return (Criteria) this;
        }

        public Criteria andGtNameGreaterThan(String value) {
            addCriterion("gt_name >", value, "gtName");
            return (Criteria) this;
        }

        public Criteria andGtNameGreaterThanOrEqualTo(String value) {
            addCriterion("gt_name >=", value, "gtName");
            return (Criteria) this;
        }

        public Criteria andGtNameLessThan(String value) {
            addCriterion("gt_name <", value, "gtName");
            return (Criteria) this;
        }

        public Criteria andGtNameLessThanOrEqualTo(String value) {
            addCriterion("gt_name <=", value, "gtName");
            return (Criteria) this;
        }

        public Criteria andGtNameLike(String value) {
            addCriterion("gt_name like", value, "gtName");
            return (Criteria) this;
        }

        public Criteria andGtNameNotLike(String value) {
            addCriterion("gt_name not like", value, "gtName");
            return (Criteria) this;
        }

        public Criteria andGtNameIn(List<String> values) {
            addCriterion("gt_name in", values, "gtName");
            return (Criteria) this;
        }

        public Criteria andGtNameNotIn(List<String> values) {
            addCriterion("gt_name not in", values, "gtName");
            return (Criteria) this;
        }

        public Criteria andGtNameBetween(String value1, String value2) {
            addCriterion("gt_name between", value1, value2, "gtName");
            return (Criteria) this;
        }

        public Criteria andGtNameNotBetween(String value1, String value2) {
            addCriterion("gt_name not between", value1, value2, "gtName");
            return (Criteria) this;
        }

        public Criteria andGNameIsNull() {
            addCriterion("g_name is null");
            return (Criteria) this;
        }

        public Criteria andGNameIsNotNull() {
            addCriterion("g_name is not null");
            return (Criteria) this;
        }

        public Criteria andGNameEqualTo(String value) {
            addCriterion("g_name =", value, "gName");
            return (Criteria) this;
        }

        public Criteria andGNameNotEqualTo(String value) {
            addCriterion("g_name <>", value, "gName");
            return (Criteria) this;
        }

        public Criteria andGNameGreaterThan(String value) {
            addCriterion("g_name >", value, "gName");
            return (Criteria) this;
        }

        public Criteria andGNameGreaterThanOrEqualTo(String value) {
            addCriterion("g_name >=", value, "gName");
            return (Criteria) this;
        }

        public Criteria andGNameLessThan(String value) {
            addCriterion("g_name <", value, "gName");
            return (Criteria) this;
        }

        public Criteria andGNameLessThanOrEqualTo(String value) {
            addCriterion("g_name <=", value, "gName");
            return (Criteria) this;
        }

        public Criteria andGNameLike(String value) {
            addCriterion("g_name like", value, "gName");
            return (Criteria) this;
        }

        public Criteria andGNameNotLike(String value) {
            addCriterion("g_name not like", value, "gName");
            return (Criteria) this;
        }

        public Criteria andGNameIn(List<String> values) {
            addCriterion("g_name in", values, "gName");
            return (Criteria) this;
        }

        public Criteria andGNameNotIn(List<String> values) {
            addCriterion("g_name not in", values, "gName");
            return (Criteria) this;
        }

        public Criteria andGNameBetween(String value1, String value2) {
            addCriterion("g_name between", value1, value2, "gName");
            return (Criteria) this;
        }

        public Criteria andGNameNotBetween(String value1, String value2) {
            addCriterion("g_name not between", value1, value2, "gName");
            return (Criteria) this;
        }

        public Criteria andGThumsIsNull() {
            addCriterion("g_thums is null");
            return (Criteria) this;
        }

        public Criteria andGThumsIsNotNull() {
            addCriterion("g_thums is not null");
            return (Criteria) this;
        }

        public Criteria andGThumsEqualTo(String value) {
            addCriterion("g_thums =", value, "gThums");
            return (Criteria) this;
        }

        public Criteria andGThumsNotEqualTo(String value) {
            addCriterion("g_thums <>", value, "gThums");
            return (Criteria) this;
        }

        public Criteria andGThumsGreaterThan(String value) {
            addCriterion("g_thums >", value, "gThums");
            return (Criteria) this;
        }

        public Criteria andGThumsGreaterThanOrEqualTo(String value) {
            addCriterion("g_thums >=", value, "gThums");
            return (Criteria) this;
        }

        public Criteria andGThumsLessThan(String value) {
            addCriterion("g_thums <", value, "gThums");
            return (Criteria) this;
        }

        public Criteria andGThumsLessThanOrEqualTo(String value) {
            addCriterion("g_thums <=", value, "gThums");
            return (Criteria) this;
        }

        public Criteria andGThumsLike(String value) {
            addCriterion("g_thums like", value, "gThums");
            return (Criteria) this;
        }

        public Criteria andGThumsNotLike(String value) {
            addCriterion("g_thums not like", value, "gThums");
            return (Criteria) this;
        }

        public Criteria andGThumsIn(List<String> values) {
            addCriterion("g_thums in", values, "gThums");
            return (Criteria) this;
        }

        public Criteria andGThumsNotIn(List<String> values) {
            addCriterion("g_thums not in", values, "gThums");
            return (Criteria) this;
        }

        public Criteria andGThumsBetween(String value1, String value2) {
            addCriterion("g_thums between", value1, value2, "gThums");
            return (Criteria) this;
        }

        public Criteria andGThumsNotBetween(String value1, String value2) {
            addCriterion("g_thums not between", value1, value2, "gThums");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_order_goods
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_order_goods
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}