package com.xuyang.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Torder implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_id
     *
     * @mbg.generated
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_no
     *
     * @mbg.generated
     */
    private String orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_createtime
     *
     * @mbg.generated
     */
    private Date orderCreatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_state
     *
     * @mbg.generated
     */
    private String orderState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_total_money
     *
     * @mbg.generated
     */
    private BigDecimal orderTotalMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_deliver_money
     *
     * @mbg.generated
     */
    private BigDecimal orderDeliverMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_paytype
     *
     * @mbg.generated
     */
    private String orderPaytype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_isself
     *
     * @mbg.generated
     */
    private String orderIsself;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_ispay
     *
     * @mbg.generated
     */
    private String orderIspay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_deliver_type
     *
     * @mbg.generated
     */
    private String orderDeliverType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_user_name
     *
     * @mbg.generated
     */
    private String orderUserName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_user_address
     *
     * @mbg.generated
     */
    private String orderUserAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_usertel
     *
     * @mbg.generated
     */
    private String orderUsertel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_phone
     *
     * @mbg.generated
     */
    private String orderPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_post_code
     *
     * @mbg.generated
     */
    private String orderPostCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_isInvoice
     *
     * @mbg.generated
     */
    private String orderIsinvoice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_invoice_client
     *
     * @mbg.generated
     */
    private String orderInvoiceClient;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_isAppraises
     *
     * @mbg.generated
     */
    private String orderIsappraises;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_isrefund
     *
     * @mbg.generated
     */
    private String orderIsrefund;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_refund_remark
     *
     * @mbg.generated
     */
    private String orderRefundRemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_src
     *
     * @mbg.generated
     */
    private String orderSrc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_glag
     *
     * @mbg.generated
     */
    private String orderGlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_payfrom
     *
     * @mbg.generated
     */
    private String orderPayfrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_real_total_money
     *
     * @mbg.generated
     */
    private BigDecimal orderRealTotalMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_from
     *
     * @mbg.generated
     */
    private String orderFrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_coupon_money
     *
     * @mbg.generated
     */
    private String orderCouponMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.tenant_sid
     *
     * @mbg.generated
     */
    private String tenantSid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_order
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_id
     *
     * @return the value of t_order.order_id
     *
     * @mbg.generated
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_id
     *
     * @param orderId the value for t_order.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_no
     *
     * @return the value of t_order.order_no
     *
     * @mbg.generated
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_no
     *
     * @param orderNo the value for t_order.order_no
     *
     * @mbg.generated
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.user_id
     *
     * @return the value of t_order.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.user_id
     *
     * @param userId the value for t_order.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_createtime
     *
     * @return the value of t_order.order_createtime
     *
     * @mbg.generated
     */
    public Date getOrderCreatetime() {
        return orderCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_createtime
     *
     * @param orderCreatetime the value for t_order.order_createtime
     *
     * @mbg.generated
     */
    public void setOrderCreatetime(Date orderCreatetime) {
        this.orderCreatetime = orderCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_state
     *
     * @return the value of t_order.order_state
     *
     * @mbg.generated
     */
    public String getOrderState() {
        return orderState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_state
     *
     * @param orderState the value for t_order.order_state
     *
     * @mbg.generated
     */
    public void setOrderState(String orderState) {
        this.orderState = orderState == null ? null : orderState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_total_money
     *
     * @return the value of t_order.order_total_money
     *
     * @mbg.generated
     */
    public BigDecimal getOrderTotalMoney() {
        return orderTotalMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_total_money
     *
     * @param orderTotalMoney the value for t_order.order_total_money
     *
     * @mbg.generated
     */
    public void setOrderTotalMoney(BigDecimal orderTotalMoney) {
        this.orderTotalMoney = orderTotalMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_deliver_money
     *
     * @return the value of t_order.order_deliver_money
     *
     * @mbg.generated
     */
    public BigDecimal getOrderDeliverMoney() {
        return orderDeliverMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_deliver_money
     *
     * @param orderDeliverMoney the value for t_order.order_deliver_money
     *
     * @mbg.generated
     */
    public void setOrderDeliverMoney(BigDecimal orderDeliverMoney) {
        this.orderDeliverMoney = orderDeliverMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_paytype
     *
     * @return the value of t_order.order_paytype
     *
     * @mbg.generated
     */
    public String getOrderPaytype() {
        return orderPaytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_paytype
     *
     * @param orderPaytype the value for t_order.order_paytype
     *
     * @mbg.generated
     */
    public void setOrderPaytype(String orderPaytype) {
        this.orderPaytype = orderPaytype == null ? null : orderPaytype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_isself
     *
     * @return the value of t_order.order_isself
     *
     * @mbg.generated
     */
    public String getOrderIsself() {
        return orderIsself;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_isself
     *
     * @param orderIsself the value for t_order.order_isself
     *
     * @mbg.generated
     */
    public void setOrderIsself(String orderIsself) {
        this.orderIsself = orderIsself == null ? null : orderIsself.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_ispay
     *
     * @return the value of t_order.order_ispay
     *
     * @mbg.generated
     */
    public String getOrderIspay() {
        return orderIspay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_ispay
     *
     * @param orderIspay the value for t_order.order_ispay
     *
     * @mbg.generated
     */
    public void setOrderIspay(String orderIspay) {
        this.orderIspay = orderIspay == null ? null : orderIspay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_deliver_type
     *
     * @return the value of t_order.order_deliver_type
     *
     * @mbg.generated
     */
    public String getOrderDeliverType() {
        return orderDeliverType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_deliver_type
     *
     * @param orderDeliverType the value for t_order.order_deliver_type
     *
     * @mbg.generated
     */
    public void setOrderDeliverType(String orderDeliverType) {
        this.orderDeliverType = orderDeliverType == null ? null : orderDeliverType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_user_name
     *
     * @return the value of t_order.order_user_name
     *
     * @mbg.generated
     */
    public String getOrderUserName() {
        return orderUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_user_name
     *
     * @param orderUserName the value for t_order.order_user_name
     *
     * @mbg.generated
     */
    public void setOrderUserName(String orderUserName) {
        this.orderUserName = orderUserName == null ? null : orderUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_user_address
     *
     * @return the value of t_order.order_user_address
     *
     * @mbg.generated
     */
    public String getOrderUserAddress() {
        return orderUserAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_user_address
     *
     * @param orderUserAddress the value for t_order.order_user_address
     *
     * @mbg.generated
     */
    public void setOrderUserAddress(String orderUserAddress) {
        this.orderUserAddress = orderUserAddress == null ? null : orderUserAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_usertel
     *
     * @return the value of t_order.order_usertel
     *
     * @mbg.generated
     */
    public String getOrderUsertel() {
        return orderUsertel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_usertel
     *
     * @param orderUsertel the value for t_order.order_usertel
     *
     * @mbg.generated
     */
    public void setOrderUsertel(String orderUsertel) {
        this.orderUsertel = orderUsertel == null ? null : orderUsertel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_phone
     *
     * @return the value of t_order.order_phone
     *
     * @mbg.generated
     */
    public String getOrderPhone() {
        return orderPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_phone
     *
     * @param orderPhone the value for t_order.order_phone
     *
     * @mbg.generated
     */
    public void setOrderPhone(String orderPhone) {
        this.orderPhone = orderPhone == null ? null : orderPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_post_code
     *
     * @return the value of t_order.order_post_code
     *
     * @mbg.generated
     */
    public String getOrderPostCode() {
        return orderPostCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_post_code
     *
     * @param orderPostCode the value for t_order.order_post_code
     *
     * @mbg.generated
     */
    public void setOrderPostCode(String orderPostCode) {
        this.orderPostCode = orderPostCode == null ? null : orderPostCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_isInvoice
     *
     * @return the value of t_order.order_isInvoice
     *
     * @mbg.generated
     */
    public String getOrderIsinvoice() {
        return orderIsinvoice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_isInvoice
     *
     * @param orderIsinvoice the value for t_order.order_isInvoice
     *
     * @mbg.generated
     */
    public void setOrderIsinvoice(String orderIsinvoice) {
        this.orderIsinvoice = orderIsinvoice == null ? null : orderIsinvoice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_invoice_client
     *
     * @return the value of t_order.order_invoice_client
     *
     * @mbg.generated
     */
    public String getOrderInvoiceClient() {
        return orderInvoiceClient;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_invoice_client
     *
     * @param orderInvoiceClient the value for t_order.order_invoice_client
     *
     * @mbg.generated
     */
    public void setOrderInvoiceClient(String orderInvoiceClient) {
        this.orderInvoiceClient = orderInvoiceClient == null ? null : orderInvoiceClient.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_isAppraises
     *
     * @return the value of t_order.order_isAppraises
     *
     * @mbg.generated
     */
    public String getOrderIsappraises() {
        return orderIsappraises;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_isAppraises
     *
     * @param orderIsappraises the value for t_order.order_isAppraises
     *
     * @mbg.generated
     */
    public void setOrderIsappraises(String orderIsappraises) {
        this.orderIsappraises = orderIsappraises == null ? null : orderIsappraises.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_isrefund
     *
     * @return the value of t_order.order_isrefund
     *
     * @mbg.generated
     */
    public String getOrderIsrefund() {
        return orderIsrefund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_isrefund
     *
     * @param orderIsrefund the value for t_order.order_isrefund
     *
     * @mbg.generated
     */
    public void setOrderIsrefund(String orderIsrefund) {
        this.orderIsrefund = orderIsrefund == null ? null : orderIsrefund.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_refund_remark
     *
     * @return the value of t_order.order_refund_remark
     *
     * @mbg.generated
     */
    public String getOrderRefundRemark() {
        return orderRefundRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_refund_remark
     *
     * @param orderRefundRemark the value for t_order.order_refund_remark
     *
     * @mbg.generated
     */
    public void setOrderRefundRemark(String orderRefundRemark) {
        this.orderRefundRemark = orderRefundRemark == null ? null : orderRefundRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_src
     *
     * @return the value of t_order.order_src
     *
     * @mbg.generated
     */
    public String getOrderSrc() {
        return orderSrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_src
     *
     * @param orderSrc the value for t_order.order_src
     *
     * @mbg.generated
     */
    public void setOrderSrc(String orderSrc) {
        this.orderSrc = orderSrc == null ? null : orderSrc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_glag
     *
     * @return the value of t_order.order_glag
     *
     * @mbg.generated
     */
    public String getOrderGlag() {
        return orderGlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_glag
     *
     * @param orderGlag the value for t_order.order_glag
     *
     * @mbg.generated
     */
    public void setOrderGlag(String orderGlag) {
        this.orderGlag = orderGlag == null ? null : orderGlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_payfrom
     *
     * @return the value of t_order.order_payfrom
     *
     * @mbg.generated
     */
    public String getOrderPayfrom() {
        return orderPayfrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_payfrom
     *
     * @param orderPayfrom the value for t_order.order_payfrom
     *
     * @mbg.generated
     */
    public void setOrderPayfrom(String orderPayfrom) {
        this.orderPayfrom = orderPayfrom == null ? null : orderPayfrom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_real_total_money
     *
     * @return the value of t_order.order_real_total_money
     *
     * @mbg.generated
     */
    public BigDecimal getOrderRealTotalMoney() {
        return orderRealTotalMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_real_total_money
     *
     * @param orderRealTotalMoney the value for t_order.order_real_total_money
     *
     * @mbg.generated
     */
    public void setOrderRealTotalMoney(BigDecimal orderRealTotalMoney) {
        this.orderRealTotalMoney = orderRealTotalMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_from
     *
     * @return the value of t_order.order_from
     *
     * @mbg.generated
     */
    public String getOrderFrom() {
        return orderFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_from
     *
     * @param orderFrom the value for t_order.order_from
     *
     * @mbg.generated
     */
    public void setOrderFrom(String orderFrom) {
        this.orderFrom = orderFrom == null ? null : orderFrom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_coupon_money
     *
     * @return the value of t_order.order_coupon_money
     *
     * @mbg.generated
     */
    public String getOrderCouponMoney() {
        return orderCouponMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_coupon_money
     *
     * @param orderCouponMoney the value for t_order.order_coupon_money
     *
     * @mbg.generated
     */
    public void setOrderCouponMoney(String orderCouponMoney) {
        this.orderCouponMoney = orderCouponMoney == null ? null : orderCouponMoney.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.tenant_sid
     *
     * @return the value of t_order.tenant_sid
     *
     * @mbg.generated
     */
    public String getTenantSid() {
        return tenantSid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.tenant_sid
     *
     * @param tenantSid the value for t_order.tenant_sid
     *
     * @mbg.generated
     */
    public void setTenantSid(String tenantSid) {
        this.tenantSid = tenantSid == null ? null : tenantSid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", orderId=").append(orderId);
        sb.append(", orderNo=").append(orderNo);
        sb.append(", userId=").append(userId);
        sb.append(", orderCreatetime=").append(orderCreatetime);
        sb.append(", orderState=").append(orderState);
        sb.append(", orderTotalMoney=").append(orderTotalMoney);
        sb.append(", orderDeliverMoney=").append(orderDeliverMoney);
        sb.append(", orderPaytype=").append(orderPaytype);
        sb.append(", orderIsself=").append(orderIsself);
        sb.append(", orderIspay=").append(orderIspay);
        sb.append(", orderDeliverType=").append(orderDeliverType);
        sb.append(", orderUserName=").append(orderUserName);
        sb.append(", orderUserAddress=").append(orderUserAddress);
        sb.append(", orderUsertel=").append(orderUsertel);
        sb.append(", orderPhone=").append(orderPhone);
        sb.append(", orderPostCode=").append(orderPostCode);
        sb.append(", orderIsinvoice=").append(orderIsinvoice);
        sb.append(", orderInvoiceClient=").append(orderInvoiceClient);
        sb.append(", orderIsappraises=").append(orderIsappraises);
        sb.append(", orderIsrefund=").append(orderIsrefund);
        sb.append(", orderRefundRemark=").append(orderRefundRemark);
        sb.append(", orderSrc=").append(orderSrc);
        sb.append(", orderGlag=").append(orderGlag);
        sb.append(", orderPayfrom=").append(orderPayfrom);
        sb.append(", orderRealTotalMoney=").append(orderRealTotalMoney);
        sb.append(", orderFrom=").append(orderFrom);
        sb.append(", orderCouponMoney=").append(orderCouponMoney);
        sb.append(", tenantSid=").append(tenantSid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}