package com.xuyang.model;

import java.io.Serializable;
import java.math.BigDecimal;

public class TorderGoods implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_goods.og_id
     *
     * @mbg.generated
     */
    private Integer ogId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_goods.order_id
     *
     * @mbg.generated
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_goods.g_id
     *
     * @mbg.generated
     */
    private Integer gId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_goods.goods_nums
     *
     * @mbg.generated
     */
    private Integer goodsNums;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_goods.goods_price
     *
     * @mbg.generated
     */
    private BigDecimal goodsPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_goods.gt_id
     *
     * @mbg.generated
     */
    private Integer gtId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_goods.gr_name
     *
     * @mbg.generated
     */
    private String grName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_goods.g_name
     *
     * @mbg.generated
     */
    private String gName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_goods.g_thums
     *
     * @mbg.generated
     */
    private String gThums;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_order_goods
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_goods.og_id
     *
     * @return the value of t_order_goods.og_id
     *
     * @mbg.generated
     */
    public Integer getOgId() {
        return ogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_goods.og_id
     *
     * @param ogId the value for t_order_goods.og_id
     *
     * @mbg.generated
     */
    public void setOgId(Integer ogId) {
        this.ogId = ogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_goods.order_id
     *
     * @return the value of t_order_goods.order_id
     *
     * @mbg.generated
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_goods.order_id
     *
     * @param orderId the value for t_order_goods.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_goods.g_id
     *
     * @return the value of t_order_goods.g_id
     *
     * @mbg.generated
     */
    public Integer getgId() {
        return gId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_goods.g_id
     *
     * @param gId the value for t_order_goods.g_id
     *
     * @mbg.generated
     */
    public void setgId(Integer gId) {
        this.gId = gId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_goods.goods_nums
     *
     * @return the value of t_order_goods.goods_nums
     *
     * @mbg.generated
     */
    public Integer getGoodsNums() {
        return goodsNums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_goods.goods_nums
     *
     * @param goodsNums the value for t_order_goods.goods_nums
     *
     * @mbg.generated
     */
    public void setGoodsNums(Integer goodsNums) {
        this.goodsNums = goodsNums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_goods.goods_price
     *
     * @return the value of t_order_goods.goods_price
     *
     * @mbg.generated
     */
    public BigDecimal getGoodsPrice() {
        return goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_goods.goods_price
     *
     * @param goodsPrice the value for t_order_goods.goods_price
     *
     * @mbg.generated
     */
    public void setGoodsPrice(BigDecimal goodsPrice) {
        this.goodsPrice = goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_goods.gt_id
     *
     * @return the value of t_order_goods.gt_id
     *
     * @mbg.generated
     */
    public Integer getGtId() {
        return gtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_goods.gt_id
     *
     * @param gtId the value for t_order_goods.gt_id
     *
     * @mbg.generated
     */
    public void setGtId(Integer gtId) {
        this.gtId = gtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_goods.gr_name
     *
     * @return the value of t_order_goods.gr_name
     *
     * @mbg.generated
     */
    public String getGrName() {
        return grName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_goods.gr_name
     *
     * @param grName the value for t_order_goods.gr_name
     *
     * @mbg.generated
     */
    public void setGrName(String grName) {
        this.grName = grName == null ? null : grName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_goods.g_name
     *
     * @return the value of t_order_goods.g_name
     *
     * @mbg.generated
     */
    public String getgName() {
        return gName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_goods.g_name
     *
     * @param gName the value for t_order_goods.g_name
     *
     * @mbg.generated
     */
    public void setgName(String gName) {
        this.gName = gName == null ? null : gName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_goods.g_thums
     *
     * @return the value of t_order_goods.g_thums
     *
     * @mbg.generated
     */
    public String getgThums() {
        return gThums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_goods.g_thums
     *
     * @param gThums the value for t_order_goods.g_thums
     *
     * @mbg.generated
     */
    public void setgThums(String gThums) {
        this.gThums = gThums == null ? null : gThums.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_goods
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", ogId=").append(ogId);
        sb.append(", orderId=").append(orderId);
        sb.append(", gId=").append(gId);
        sb.append(", goodsNums=").append(goodsNums);
        sb.append(", goodsPrice=").append(goodsPrice);
        sb.append(", gtId=").append(gtId);
        sb.append(", grName=").append(grName);
        sb.append(", gName=").append(gName);
        sb.append(", gThums=").append(gThums);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}