package com.xuyang.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TuserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated
     */
    public TuserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_user
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserNicknameIsNull() {
            addCriterion("user_nickname is null");
            return (Criteria) this;
        }

        public Criteria andUserNicknameIsNotNull() {
            addCriterion("user_nickname is not null");
            return (Criteria) this;
        }

        public Criteria andUserNicknameEqualTo(String value) {
            addCriterion("user_nickname =", value, "userNickname");
            return (Criteria) this;
        }

        public Criteria andUserNicknameNotEqualTo(String value) {
            addCriterion("user_nickname <>", value, "userNickname");
            return (Criteria) this;
        }

        public Criteria andUserNicknameGreaterThan(String value) {
            addCriterion("user_nickname >", value, "userNickname");
            return (Criteria) this;
        }

        public Criteria andUserNicknameGreaterThanOrEqualTo(String value) {
            addCriterion("user_nickname >=", value, "userNickname");
            return (Criteria) this;
        }

        public Criteria andUserNicknameLessThan(String value) {
            addCriterion("user_nickname <", value, "userNickname");
            return (Criteria) this;
        }

        public Criteria andUserNicknameLessThanOrEqualTo(String value) {
            addCriterion("user_nickname <=", value, "userNickname");
            return (Criteria) this;
        }

        public Criteria andUserNicknameLike(String value) {
            addCriterion("user_nickname like", value, "userNickname");
            return (Criteria) this;
        }

        public Criteria andUserNicknameNotLike(String value) {
            addCriterion("user_nickname not like", value, "userNickname");
            return (Criteria) this;
        }

        public Criteria andUserNicknameIn(List<String> values) {
            addCriterion("user_nickname in", values, "userNickname");
            return (Criteria) this;
        }

        public Criteria andUserNicknameNotIn(List<String> values) {
            addCriterion("user_nickname not in", values, "userNickname");
            return (Criteria) this;
        }

        public Criteria andUserNicknameBetween(String value1, String value2) {
            addCriterion("user_nickname between", value1, value2, "userNickname");
            return (Criteria) this;
        }

        public Criteria andUserNicknameNotBetween(String value1, String value2) {
            addCriterion("user_nickname not between", value1, value2, "userNickname");
            return (Criteria) this;
        }

        public Criteria andUserHeadIsNull() {
            addCriterion("user_head is null");
            return (Criteria) this;
        }

        public Criteria andUserHeadIsNotNull() {
            addCriterion("user_head is not null");
            return (Criteria) this;
        }

        public Criteria andUserHeadEqualTo(String value) {
            addCriterion("user_head =", value, "userHead");
            return (Criteria) this;
        }

        public Criteria andUserHeadNotEqualTo(String value) {
            addCriterion("user_head <>", value, "userHead");
            return (Criteria) this;
        }

        public Criteria andUserHeadGreaterThan(String value) {
            addCriterion("user_head >", value, "userHead");
            return (Criteria) this;
        }

        public Criteria andUserHeadGreaterThanOrEqualTo(String value) {
            addCriterion("user_head >=", value, "userHead");
            return (Criteria) this;
        }

        public Criteria andUserHeadLessThan(String value) {
            addCriterion("user_head <", value, "userHead");
            return (Criteria) this;
        }

        public Criteria andUserHeadLessThanOrEqualTo(String value) {
            addCriterion("user_head <=", value, "userHead");
            return (Criteria) this;
        }

        public Criteria andUserHeadLike(String value) {
            addCriterion("user_head like", value, "userHead");
            return (Criteria) this;
        }

        public Criteria andUserHeadNotLike(String value) {
            addCriterion("user_head not like", value, "userHead");
            return (Criteria) this;
        }

        public Criteria andUserHeadIn(List<String> values) {
            addCriterion("user_head in", values, "userHead");
            return (Criteria) this;
        }

        public Criteria andUserHeadNotIn(List<String> values) {
            addCriterion("user_head not in", values, "userHead");
            return (Criteria) this;
        }

        public Criteria andUserHeadBetween(String value1, String value2) {
            addCriterion("user_head between", value1, value2, "userHead");
            return (Criteria) this;
        }

        public Criteria andUserHeadNotBetween(String value1, String value2) {
            addCriterion("user_head not between", value1, value2, "userHead");
            return (Criteria) this;
        }

        public Criteria andUserPhoneIsNull() {
            addCriterion("user_phone is null");
            return (Criteria) this;
        }

        public Criteria andUserPhoneIsNotNull() {
            addCriterion("user_phone is not null");
            return (Criteria) this;
        }

        public Criteria andUserPhoneEqualTo(String value) {
            addCriterion("user_phone =", value, "userPhone");
            return (Criteria) this;
        }

        public Criteria andUserPhoneNotEqualTo(String value) {
            addCriterion("user_phone <>", value, "userPhone");
            return (Criteria) this;
        }

        public Criteria andUserPhoneGreaterThan(String value) {
            addCriterion("user_phone >", value, "userPhone");
            return (Criteria) this;
        }

        public Criteria andUserPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("user_phone >=", value, "userPhone");
            return (Criteria) this;
        }

        public Criteria andUserPhoneLessThan(String value) {
            addCriterion("user_phone <", value, "userPhone");
            return (Criteria) this;
        }

        public Criteria andUserPhoneLessThanOrEqualTo(String value) {
            addCriterion("user_phone <=", value, "userPhone");
            return (Criteria) this;
        }

        public Criteria andUserPhoneLike(String value) {
            addCriterion("user_phone like", value, "userPhone");
            return (Criteria) this;
        }

        public Criteria andUserPhoneNotLike(String value) {
            addCriterion("user_phone not like", value, "userPhone");
            return (Criteria) this;
        }

        public Criteria andUserPhoneIn(List<String> values) {
            addCriterion("user_phone in", values, "userPhone");
            return (Criteria) this;
        }

        public Criteria andUserPhoneNotIn(List<String> values) {
            addCriterion("user_phone not in", values, "userPhone");
            return (Criteria) this;
        }

        public Criteria andUserPhoneBetween(String value1, String value2) {
            addCriterion("user_phone between", value1, value2, "userPhone");
            return (Criteria) this;
        }

        public Criteria andUserPhoneNotBetween(String value1, String value2) {
            addCriterion("user_phone not between", value1, value2, "userPhone");
            return (Criteria) this;
        }

        public Criteria andUserSexIsNull() {
            addCriterion("user_sex is null");
            return (Criteria) this;
        }

        public Criteria andUserSexIsNotNull() {
            addCriterion("user_sex is not null");
            return (Criteria) this;
        }

        public Criteria andUserSexEqualTo(String value) {
            addCriterion("user_sex =", value, "userSex");
            return (Criteria) this;
        }

        public Criteria andUserSexNotEqualTo(String value) {
            addCriterion("user_sex <>", value, "userSex");
            return (Criteria) this;
        }

        public Criteria andUserSexGreaterThan(String value) {
            addCriterion("user_sex >", value, "userSex");
            return (Criteria) this;
        }

        public Criteria andUserSexGreaterThanOrEqualTo(String value) {
            addCriterion("user_sex >=", value, "userSex");
            return (Criteria) this;
        }

        public Criteria andUserSexLessThan(String value) {
            addCriterion("user_sex <", value, "userSex");
            return (Criteria) this;
        }

        public Criteria andUserSexLessThanOrEqualTo(String value) {
            addCriterion("user_sex <=", value, "userSex");
            return (Criteria) this;
        }

        public Criteria andUserSexLike(String value) {
            addCriterion("user_sex like", value, "userSex");
            return (Criteria) this;
        }

        public Criteria andUserSexNotLike(String value) {
            addCriterion("user_sex not like", value, "userSex");
            return (Criteria) this;
        }

        public Criteria andUserSexIn(List<String> values) {
            addCriterion("user_sex in", values, "userSex");
            return (Criteria) this;
        }

        public Criteria andUserSexNotIn(List<String> values) {
            addCriterion("user_sex not in", values, "userSex");
            return (Criteria) this;
        }

        public Criteria andUserSexBetween(String value1, String value2) {
            addCriterion("user_sex between", value1, value2, "userSex");
            return (Criteria) this;
        }

        public Criteria andUserSexNotBetween(String value1, String value2) {
            addCriterion("user_sex not between", value1, value2, "userSex");
            return (Criteria) this;
        }

        public Criteria andUserAddressIsNull() {
            addCriterion("user_address is null");
            return (Criteria) this;
        }

        public Criteria andUserAddressIsNotNull() {
            addCriterion("user_address is not null");
            return (Criteria) this;
        }

        public Criteria andUserAddressEqualTo(String value) {
            addCriterion("user_address =", value, "userAddress");
            return (Criteria) this;
        }

        public Criteria andUserAddressNotEqualTo(String value) {
            addCriterion("user_address <>", value, "userAddress");
            return (Criteria) this;
        }

        public Criteria andUserAddressGreaterThan(String value) {
            addCriterion("user_address >", value, "userAddress");
            return (Criteria) this;
        }

        public Criteria andUserAddressGreaterThanOrEqualTo(String value) {
            addCriterion("user_address >=", value, "userAddress");
            return (Criteria) this;
        }

        public Criteria andUserAddressLessThan(String value) {
            addCriterion("user_address <", value, "userAddress");
            return (Criteria) this;
        }

        public Criteria andUserAddressLessThanOrEqualTo(String value) {
            addCriterion("user_address <=", value, "userAddress");
            return (Criteria) this;
        }

        public Criteria andUserAddressLike(String value) {
            addCriterion("user_address like", value, "userAddress");
            return (Criteria) this;
        }

        public Criteria andUserAddressNotLike(String value) {
            addCriterion("user_address not like", value, "userAddress");
            return (Criteria) this;
        }

        public Criteria andUserAddressIn(List<String> values) {
            addCriterion("user_address in", values, "userAddress");
            return (Criteria) this;
        }

        public Criteria andUserAddressNotIn(List<String> values) {
            addCriterion("user_address not in", values, "userAddress");
            return (Criteria) this;
        }

        public Criteria andUserAddressBetween(String value1, String value2) {
            addCriterion("user_address between", value1, value2, "userAddress");
            return (Criteria) this;
        }

        public Criteria andUserAddressNotBetween(String value1, String value2) {
            addCriterion("user_address not between", value1, value2, "userAddress");
            return (Criteria) this;
        }

        public Criteria andUserDateIsNull() {
            addCriterion("user_date is null");
            return (Criteria) this;
        }

        public Criteria andUserDateIsNotNull() {
            addCriterion("user_date is not null");
            return (Criteria) this;
        }

        public Criteria andUserDateEqualTo(String value) {
            addCriterion("user_date =", value, "userDate");
            return (Criteria) this;
        }

        public Criteria andUserDateNotEqualTo(String value) {
            addCriterion("user_date <>", value, "userDate");
            return (Criteria) this;
        }

        public Criteria andUserDateGreaterThan(String value) {
            addCriterion("user_date >", value, "userDate");
            return (Criteria) this;
        }

        public Criteria andUserDateGreaterThanOrEqualTo(String value) {
            addCriterion("user_date >=", value, "userDate");
            return (Criteria) this;
        }

        public Criteria andUserDateLessThan(String value) {
            addCriterion("user_date <", value, "userDate");
            return (Criteria) this;
        }

        public Criteria andUserDateLessThanOrEqualTo(String value) {
            addCriterion("user_date <=", value, "userDate");
            return (Criteria) this;
        }

        public Criteria andUserDateLike(String value) {
            addCriterion("user_date like", value, "userDate");
            return (Criteria) this;
        }

        public Criteria andUserDateNotLike(String value) {
            addCriterion("user_date not like", value, "userDate");
            return (Criteria) this;
        }

        public Criteria andUserDateIn(List<String> values) {
            addCriterion("user_date in", values, "userDate");
            return (Criteria) this;
        }

        public Criteria andUserDateNotIn(List<String> values) {
            addCriterion("user_date not in", values, "userDate");
            return (Criteria) this;
        }

        public Criteria andUserDateBetween(String value1, String value2) {
            addCriterion("user_date between", value1, value2, "userDate");
            return (Criteria) this;
        }

        public Criteria andUserDateNotBetween(String value1, String value2) {
            addCriterion("user_date not between", value1, value2, "userDate");
            return (Criteria) this;
        }

        public Criteria andUserPwdIsNull() {
            addCriterion("user_pwd is null");
            return (Criteria) this;
        }

        public Criteria andUserPwdIsNotNull() {
            addCriterion("user_pwd is not null");
            return (Criteria) this;
        }

        public Criteria andUserPwdEqualTo(String value) {
            addCriterion("user_pwd =", value, "userPwd");
            return (Criteria) this;
        }

        public Criteria andUserPwdNotEqualTo(String value) {
            addCriterion("user_pwd <>", value, "userPwd");
            return (Criteria) this;
        }

        public Criteria andUserPwdGreaterThan(String value) {
            addCriterion("user_pwd >", value, "userPwd");
            return (Criteria) this;
        }

        public Criteria andUserPwdGreaterThanOrEqualTo(String value) {
            addCriterion("user_pwd >=", value, "userPwd");
            return (Criteria) this;
        }

        public Criteria andUserPwdLessThan(String value) {
            addCriterion("user_pwd <", value, "userPwd");
            return (Criteria) this;
        }

        public Criteria andUserPwdLessThanOrEqualTo(String value) {
            addCriterion("user_pwd <=", value, "userPwd");
            return (Criteria) this;
        }

        public Criteria andUserPwdLike(String value) {
            addCriterion("user_pwd like", value, "userPwd");
            return (Criteria) this;
        }

        public Criteria andUserPwdNotLike(String value) {
            addCriterion("user_pwd not like", value, "userPwd");
            return (Criteria) this;
        }

        public Criteria andUserPwdIn(List<String> values) {
            addCriterion("user_pwd in", values, "userPwd");
            return (Criteria) this;
        }

        public Criteria andUserPwdNotIn(List<String> values) {
            addCriterion("user_pwd not in", values, "userPwd");
            return (Criteria) this;
        }

        public Criteria andUserPwdBetween(String value1, String value2) {
            addCriterion("user_pwd between", value1, value2, "userPwd");
            return (Criteria) this;
        }

        public Criteria andUserPwdNotBetween(String value1, String value2) {
            addCriterion("user_pwd not between", value1, value2, "userPwd");
            return (Criteria) this;
        }

        public Criteria andUserRegionIsNull() {
            addCriterion("user_region is null");
            return (Criteria) this;
        }

        public Criteria andUserRegionIsNotNull() {
            addCriterion("user_region is not null");
            return (Criteria) this;
        }

        public Criteria andUserRegionEqualTo(String value) {
            addCriterion("user_region =", value, "userRegion");
            return (Criteria) this;
        }

        public Criteria andUserRegionNotEqualTo(String value) {
            addCriterion("user_region <>", value, "userRegion");
            return (Criteria) this;
        }

        public Criteria andUserRegionGreaterThan(String value) {
            addCriterion("user_region >", value, "userRegion");
            return (Criteria) this;
        }

        public Criteria andUserRegionGreaterThanOrEqualTo(String value) {
            addCriterion("user_region >=", value, "userRegion");
            return (Criteria) this;
        }

        public Criteria andUserRegionLessThan(String value) {
            addCriterion("user_region <", value, "userRegion");
            return (Criteria) this;
        }

        public Criteria andUserRegionLessThanOrEqualTo(String value) {
            addCriterion("user_region <=", value, "userRegion");
            return (Criteria) this;
        }

        public Criteria andUserRegionLike(String value) {
            addCriterion("user_region like", value, "userRegion");
            return (Criteria) this;
        }

        public Criteria andUserRegionNotLike(String value) {
            addCriterion("user_region not like", value, "userRegion");
            return (Criteria) this;
        }

        public Criteria andUserRegionIn(List<String> values) {
            addCriterion("user_region in", values, "userRegion");
            return (Criteria) this;
        }

        public Criteria andUserRegionNotIn(List<String> values) {
            addCriterion("user_region not in", values, "userRegion");
            return (Criteria) this;
        }

        public Criteria andUserRegionBetween(String value1, String value2) {
            addCriterion("user_region between", value1, value2, "userRegion");
            return (Criteria) this;
        }

        public Criteria andUserRegionNotBetween(String value1, String value2) {
            addCriterion("user_region not between", value1, value2, "userRegion");
            return (Criteria) this;
        }

        public Criteria andUserQqsoleIsNull() {
            addCriterion("user_qqsole is null");
            return (Criteria) this;
        }

        public Criteria andUserQqsoleIsNotNull() {
            addCriterion("user_qqsole is not null");
            return (Criteria) this;
        }

        public Criteria andUserQqsoleEqualTo(String value) {
            addCriterion("user_qqsole =", value, "userQqsole");
            return (Criteria) this;
        }

        public Criteria andUserQqsoleNotEqualTo(String value) {
            addCriterion("user_qqsole <>", value, "userQqsole");
            return (Criteria) this;
        }

        public Criteria andUserQqsoleGreaterThan(String value) {
            addCriterion("user_qqsole >", value, "userQqsole");
            return (Criteria) this;
        }

        public Criteria andUserQqsoleGreaterThanOrEqualTo(String value) {
            addCriterion("user_qqsole >=", value, "userQqsole");
            return (Criteria) this;
        }

        public Criteria andUserQqsoleLessThan(String value) {
            addCriterion("user_qqsole <", value, "userQqsole");
            return (Criteria) this;
        }

        public Criteria andUserQqsoleLessThanOrEqualTo(String value) {
            addCriterion("user_qqsole <=", value, "userQqsole");
            return (Criteria) this;
        }

        public Criteria andUserQqsoleLike(String value) {
            addCriterion("user_qqsole like", value, "userQqsole");
            return (Criteria) this;
        }

        public Criteria andUserQqsoleNotLike(String value) {
            addCriterion("user_qqsole not like", value, "userQqsole");
            return (Criteria) this;
        }

        public Criteria andUserQqsoleIn(List<String> values) {
            addCriterion("user_qqsole in", values, "userQqsole");
            return (Criteria) this;
        }

        public Criteria andUserQqsoleNotIn(List<String> values) {
            addCriterion("user_qqsole not in", values, "userQqsole");
            return (Criteria) this;
        }

        public Criteria andUserQqsoleBetween(String value1, String value2) {
            addCriterion("user_qqsole between", value1, value2, "userQqsole");
            return (Criteria) this;
        }

        public Criteria andUserQqsoleNotBetween(String value1, String value2) {
            addCriterion("user_qqsole not between", value1, value2, "userQqsole");
            return (Criteria) this;
        }

        public Criteria andUserWxsoleIsNull() {
            addCriterion("user_wxsole is null");
            return (Criteria) this;
        }

        public Criteria andUserWxsoleIsNotNull() {
            addCriterion("user_wxsole is not null");
            return (Criteria) this;
        }

        public Criteria andUserWxsoleEqualTo(String value) {
            addCriterion("user_wxsole =", value, "userWxsole");
            return (Criteria) this;
        }

        public Criteria andUserWxsoleNotEqualTo(String value) {
            addCriterion("user_wxsole <>", value, "userWxsole");
            return (Criteria) this;
        }

        public Criteria andUserWxsoleGreaterThan(String value) {
            addCriterion("user_wxsole >", value, "userWxsole");
            return (Criteria) this;
        }

        public Criteria andUserWxsoleGreaterThanOrEqualTo(String value) {
            addCriterion("user_wxsole >=", value, "userWxsole");
            return (Criteria) this;
        }

        public Criteria andUserWxsoleLessThan(String value) {
            addCriterion("user_wxsole <", value, "userWxsole");
            return (Criteria) this;
        }

        public Criteria andUserWxsoleLessThanOrEqualTo(String value) {
            addCriterion("user_wxsole <=", value, "userWxsole");
            return (Criteria) this;
        }

        public Criteria andUserWxsoleLike(String value) {
            addCriterion("user_wxsole like", value, "userWxsole");
            return (Criteria) this;
        }

        public Criteria andUserWxsoleNotLike(String value) {
            addCriterion("user_wxsole not like", value, "userWxsole");
            return (Criteria) this;
        }

        public Criteria andUserWxsoleIn(List<String> values) {
            addCriterion("user_wxsole in", values, "userWxsole");
            return (Criteria) this;
        }

        public Criteria andUserWxsoleNotIn(List<String> values) {
            addCriterion("user_wxsole not in", values, "userWxsole");
            return (Criteria) this;
        }

        public Criteria andUserWxsoleBetween(String value1, String value2) {
            addCriterion("user_wxsole between", value1, value2, "userWxsole");
            return (Criteria) this;
        }

        public Criteria andUserWxsoleNotBetween(String value1, String value2) {
            addCriterion("user_wxsole not between", value1, value2, "userWxsole");
            return (Criteria) this;
        }

        public Criteria andUserWbsoleIsNull() {
            addCriterion("user_wbsole is null");
            return (Criteria) this;
        }

        public Criteria andUserWbsoleIsNotNull() {
            addCriterion("user_wbsole is not null");
            return (Criteria) this;
        }

        public Criteria andUserWbsoleEqualTo(String value) {
            addCriterion("user_wbsole =", value, "userWbsole");
            return (Criteria) this;
        }

        public Criteria andUserWbsoleNotEqualTo(String value) {
            addCriterion("user_wbsole <>", value, "userWbsole");
            return (Criteria) this;
        }

        public Criteria andUserWbsoleGreaterThan(String value) {
            addCriterion("user_wbsole >", value, "userWbsole");
            return (Criteria) this;
        }

        public Criteria andUserWbsoleGreaterThanOrEqualTo(String value) {
            addCriterion("user_wbsole >=", value, "userWbsole");
            return (Criteria) this;
        }

        public Criteria andUserWbsoleLessThan(String value) {
            addCriterion("user_wbsole <", value, "userWbsole");
            return (Criteria) this;
        }

        public Criteria andUserWbsoleLessThanOrEqualTo(String value) {
            addCriterion("user_wbsole <=", value, "userWbsole");
            return (Criteria) this;
        }

        public Criteria andUserWbsoleLike(String value) {
            addCriterion("user_wbsole like", value, "userWbsole");
            return (Criteria) this;
        }

        public Criteria andUserWbsoleNotLike(String value) {
            addCriterion("user_wbsole not like", value, "userWbsole");
            return (Criteria) this;
        }

        public Criteria andUserWbsoleIn(List<String> values) {
            addCriterion("user_wbsole in", values, "userWbsole");
            return (Criteria) this;
        }

        public Criteria andUserWbsoleNotIn(List<String> values) {
            addCriterion("user_wbsole not in", values, "userWbsole");
            return (Criteria) this;
        }

        public Criteria andUserWbsoleBetween(String value1, String value2) {
            addCriterion("user_wbsole between", value1, value2, "userWbsole");
            return (Criteria) this;
        }

        public Criteria andUserWbsoleNotBetween(String value1, String value2) {
            addCriterion("user_wbsole not between", value1, value2, "userWbsole");
            return (Criteria) this;
        }

        public Criteria andTenantSidIsNull() {
            addCriterion("tenant_sid is null");
            return (Criteria) this;
        }

        public Criteria andTenantSidIsNotNull() {
            addCriterion("tenant_sid is not null");
            return (Criteria) this;
        }

        public Criteria andTenantSidEqualTo(String value) {
            addCriterion("tenant_sid =", value, "tenantSid");
            return (Criteria) this;
        }

        public Criteria andTenantSidNotEqualTo(String value) {
            addCriterion("tenant_sid <>", value, "tenantSid");
            return (Criteria) this;
        }

        public Criteria andTenantSidGreaterThan(String value) {
            addCriterion("tenant_sid >", value, "tenantSid");
            return (Criteria) this;
        }

        public Criteria andTenantSidGreaterThanOrEqualTo(String value) {
            addCriterion("tenant_sid >=", value, "tenantSid");
            return (Criteria) this;
        }

        public Criteria andTenantSidLessThan(String value) {
            addCriterion("tenant_sid <", value, "tenantSid");
            return (Criteria) this;
        }

        public Criteria andTenantSidLessThanOrEqualTo(String value) {
            addCriterion("tenant_sid <=", value, "tenantSid");
            return (Criteria) this;
        }

        public Criteria andTenantSidLike(String value) {
            addCriterion("tenant_sid like", value, "tenantSid");
            return (Criteria) this;
        }

        public Criteria andTenantSidNotLike(String value) {
            addCriterion("tenant_sid not like", value, "tenantSid");
            return (Criteria) this;
        }

        public Criteria andTenantSidIn(List<String> values) {
            addCriterion("tenant_sid in", values, "tenantSid");
            return (Criteria) this;
        }

        public Criteria andTenantSidNotIn(List<String> values) {
            addCriterion("tenant_sid not in", values, "tenantSid");
            return (Criteria) this;
        }

        public Criteria andTenantSidBetween(String value1, String value2) {
            addCriterion("tenant_sid between", value1, value2, "tenantSid");
            return (Criteria) this;
        }

        public Criteria andTenantSidNotBetween(String value1, String value2) {
            addCriterion("tenant_sid not between", value1, value2, "tenantSid");
            return (Criteria) this;
        }

        public Criteria andTenantAddressIsNull() {
            addCriterion("tenant_address is null");
            return (Criteria) this;
        }

        public Criteria andTenantAddressIsNotNull() {
            addCriterion("tenant_address is not null");
            return (Criteria) this;
        }

        public Criteria andTenantAddressEqualTo(String value) {
            addCriterion("tenant_address =", value, "tenantAddress");
            return (Criteria) this;
        }

        public Criteria andTenantAddressNotEqualTo(String value) {
            addCriterion("tenant_address <>", value, "tenantAddress");
            return (Criteria) this;
        }

        public Criteria andTenantAddressGreaterThan(String value) {
            addCriterion("tenant_address >", value, "tenantAddress");
            return (Criteria) this;
        }

        public Criteria andTenantAddressGreaterThanOrEqualTo(String value) {
            addCriterion("tenant_address >=", value, "tenantAddress");
            return (Criteria) this;
        }

        public Criteria andTenantAddressLessThan(String value) {
            addCriterion("tenant_address <", value, "tenantAddress");
            return (Criteria) this;
        }

        public Criteria andTenantAddressLessThanOrEqualTo(String value) {
            addCriterion("tenant_address <=", value, "tenantAddress");
            return (Criteria) this;
        }

        public Criteria andTenantAddressLike(String value) {
            addCriterion("tenant_address like", value, "tenantAddress");
            return (Criteria) this;
        }

        public Criteria andTenantAddressNotLike(String value) {
            addCriterion("tenant_address not like", value, "tenantAddress");
            return (Criteria) this;
        }

        public Criteria andTenantAddressIn(List<String> values) {
            addCriterion("tenant_address in", values, "tenantAddress");
            return (Criteria) this;
        }

        public Criteria andTenantAddressNotIn(List<String> values) {
            addCriterion("tenant_address not in", values, "tenantAddress");
            return (Criteria) this;
        }

        public Criteria andTenantAddressBetween(String value1, String value2) {
            addCriterion("tenant_address between", value1, value2, "tenantAddress");
            return (Criteria) this;
        }

        public Criteria andTenantAddressNotBetween(String value1, String value2) {
            addCriterion("tenant_address not between", value1, value2, "tenantAddress");
            return (Criteria) this;
        }

        public Criteria andTenantBankEmailIsNull() {
            addCriterion("tenant_bank_email is null");
            return (Criteria) this;
        }

        public Criteria andTenantBankEmailIsNotNull() {
            addCriterion("tenant_bank_email is not null");
            return (Criteria) this;
        }

        public Criteria andTenantBankEmailEqualTo(String value) {
            addCriterion("tenant_bank_email =", value, "tenantBankEmail");
            return (Criteria) this;
        }

        public Criteria andTenantBankEmailNotEqualTo(String value) {
            addCriterion("tenant_bank_email <>", value, "tenantBankEmail");
            return (Criteria) this;
        }

        public Criteria andTenantBankEmailGreaterThan(String value) {
            addCriterion("tenant_bank_email >", value, "tenantBankEmail");
            return (Criteria) this;
        }

        public Criteria andTenantBankEmailGreaterThanOrEqualTo(String value) {
            addCriterion("tenant_bank_email >=", value, "tenantBankEmail");
            return (Criteria) this;
        }

        public Criteria andTenantBankEmailLessThan(String value) {
            addCriterion("tenant_bank_email <", value, "tenantBankEmail");
            return (Criteria) this;
        }

        public Criteria andTenantBankEmailLessThanOrEqualTo(String value) {
            addCriterion("tenant_bank_email <=", value, "tenantBankEmail");
            return (Criteria) this;
        }

        public Criteria andTenantBankEmailLike(String value) {
            addCriterion("tenant_bank_email like", value, "tenantBankEmail");
            return (Criteria) this;
        }

        public Criteria andTenantBankEmailNotLike(String value) {
            addCriterion("tenant_bank_email not like", value, "tenantBankEmail");
            return (Criteria) this;
        }

        public Criteria andTenantBankEmailIn(List<String> values) {
            addCriterion("tenant_bank_email in", values, "tenantBankEmail");
            return (Criteria) this;
        }

        public Criteria andTenantBankEmailNotIn(List<String> values) {
            addCriterion("tenant_bank_email not in", values, "tenantBankEmail");
            return (Criteria) this;
        }

        public Criteria andTenantBankEmailBetween(String value1, String value2) {
            addCriterion("tenant_bank_email between", value1, value2, "tenantBankEmail");
            return (Criteria) this;
        }

        public Criteria andTenantBankEmailNotBetween(String value1, String value2) {
            addCriterion("tenant_bank_email not between", value1, value2, "tenantBankEmail");
            return (Criteria) this;
        }

        public Criteria andTenantEnterinfoIsNull() {
            addCriterion("tenant_enterinfo is null");
            return (Criteria) this;
        }

        public Criteria andTenantEnterinfoIsNotNull() {
            addCriterion("tenant_enterinfo is not null");
            return (Criteria) this;
        }

        public Criteria andTenantEnterinfoEqualTo(String value) {
            addCriterion("tenant_enterinfo =", value, "tenantEnterinfo");
            return (Criteria) this;
        }

        public Criteria andTenantEnterinfoNotEqualTo(String value) {
            addCriterion("tenant_enterinfo <>", value, "tenantEnterinfo");
            return (Criteria) this;
        }

        public Criteria andTenantEnterinfoGreaterThan(String value) {
            addCriterion("tenant_enterinfo >", value, "tenantEnterinfo");
            return (Criteria) this;
        }

        public Criteria andTenantEnterinfoGreaterThanOrEqualTo(String value) {
            addCriterion("tenant_enterinfo >=", value, "tenantEnterinfo");
            return (Criteria) this;
        }

        public Criteria andTenantEnterinfoLessThan(String value) {
            addCriterion("tenant_enterinfo <", value, "tenantEnterinfo");
            return (Criteria) this;
        }

        public Criteria andTenantEnterinfoLessThanOrEqualTo(String value) {
            addCriterion("tenant_enterinfo <=", value, "tenantEnterinfo");
            return (Criteria) this;
        }

        public Criteria andTenantEnterinfoLike(String value) {
            addCriterion("tenant_enterinfo like", value, "tenantEnterinfo");
            return (Criteria) this;
        }

        public Criteria andTenantEnterinfoNotLike(String value) {
            addCriterion("tenant_enterinfo not like", value, "tenantEnterinfo");
            return (Criteria) this;
        }

        public Criteria andTenantEnterinfoIn(List<String> values) {
            addCriterion("tenant_enterinfo in", values, "tenantEnterinfo");
            return (Criteria) this;
        }

        public Criteria andTenantEnterinfoNotIn(List<String> values) {
            addCriterion("tenant_enterinfo not in", values, "tenantEnterinfo");
            return (Criteria) this;
        }

        public Criteria andTenantEnterinfoBetween(String value1, String value2) {
            addCriterion("tenant_enterinfo between", value1, value2, "tenantEnterinfo");
            return (Criteria) this;
        }

        public Criteria andTenantEnterinfoNotBetween(String value1, String value2) {
            addCriterion("tenant_enterinfo not between", value1, value2, "tenantEnterinfo");
            return (Criteria) this;
        }

        public Criteria andUserIdentityIsNull() {
            addCriterion("user_identity is null");
            return (Criteria) this;
        }

        public Criteria andUserIdentityIsNotNull() {
            addCriterion("user_identity is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdentityEqualTo(String value) {
            addCriterion("user_identity =", value, "userIdentity");
            return (Criteria) this;
        }

        public Criteria andUserIdentityNotEqualTo(String value) {
            addCriterion("user_identity <>", value, "userIdentity");
            return (Criteria) this;
        }

        public Criteria andUserIdentityGreaterThan(String value) {
            addCriterion("user_identity >", value, "userIdentity");
            return (Criteria) this;
        }

        public Criteria andUserIdentityGreaterThanOrEqualTo(String value) {
            addCriterion("user_identity >=", value, "userIdentity");
            return (Criteria) this;
        }

        public Criteria andUserIdentityLessThan(String value) {
            addCriterion("user_identity <", value, "userIdentity");
            return (Criteria) this;
        }

        public Criteria andUserIdentityLessThanOrEqualTo(String value) {
            addCriterion("user_identity <=", value, "userIdentity");
            return (Criteria) this;
        }

        public Criteria andUserIdentityLike(String value) {
            addCriterion("user_identity like", value, "userIdentity");
            return (Criteria) this;
        }

        public Criteria andUserIdentityNotLike(String value) {
            addCriterion("user_identity not like", value, "userIdentity");
            return (Criteria) this;
        }

        public Criteria andUserIdentityIn(List<String> values) {
            addCriterion("user_identity in", values, "userIdentity");
            return (Criteria) this;
        }

        public Criteria andUserIdentityNotIn(List<String> values) {
            addCriterion("user_identity not in", values, "userIdentity");
            return (Criteria) this;
        }

        public Criteria andUserIdentityBetween(String value1, String value2) {
            addCriterion("user_identity between", value1, value2, "userIdentity");
            return (Criteria) this;
        }

        public Criteria andUserIdentityNotBetween(String value1, String value2) {
            addCriterion("user_identity not between", value1, value2, "userIdentity");
            return (Criteria) this;
        }

        public Criteria andShopNameIsNull() {
            addCriterion("shop_name is null");
            return (Criteria) this;
        }

        public Criteria andShopNameIsNotNull() {
            addCriterion("shop_name is not null");
            return (Criteria) this;
        }

        public Criteria andShopNameEqualTo(String value) {
            addCriterion("shop_name =", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameNotEqualTo(String value) {
            addCriterion("shop_name <>", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameGreaterThan(String value) {
            addCriterion("shop_name >", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameGreaterThanOrEqualTo(String value) {
            addCriterion("shop_name >=", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameLessThan(String value) {
            addCriterion("shop_name <", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameLessThanOrEqualTo(String value) {
            addCriterion("shop_name <=", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameLike(String value) {
            addCriterion("shop_name like", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameNotLike(String value) {
            addCriterion("shop_name not like", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameIn(List<String> values) {
            addCriterion("shop_name in", values, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameNotIn(List<String> values) {
            addCriterion("shop_name not in", values, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameBetween(String value1, String value2) {
            addCriterion("shop_name between", value1, value2, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameNotBetween(String value1, String value2) {
            addCriterion("shop_name not between", value1, value2, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopAddressIsNull() {
            addCriterion("shop_address is null");
            return (Criteria) this;
        }

        public Criteria andShopAddressIsNotNull() {
            addCriterion("shop_address is not null");
            return (Criteria) this;
        }

        public Criteria andShopAddressEqualTo(String value) {
            addCriterion("shop_address =", value, "shopAddress");
            return (Criteria) this;
        }

        public Criteria andShopAddressNotEqualTo(String value) {
            addCriterion("shop_address <>", value, "shopAddress");
            return (Criteria) this;
        }

        public Criteria andShopAddressGreaterThan(String value) {
            addCriterion("shop_address >", value, "shopAddress");
            return (Criteria) this;
        }

        public Criteria andShopAddressGreaterThanOrEqualTo(String value) {
            addCriterion("shop_address >=", value, "shopAddress");
            return (Criteria) this;
        }

        public Criteria andShopAddressLessThan(String value) {
            addCriterion("shop_address <", value, "shopAddress");
            return (Criteria) this;
        }

        public Criteria andShopAddressLessThanOrEqualTo(String value) {
            addCriterion("shop_address <=", value, "shopAddress");
            return (Criteria) this;
        }

        public Criteria andShopAddressLike(String value) {
            addCriterion("shop_address like", value, "shopAddress");
            return (Criteria) this;
        }

        public Criteria andShopAddressNotLike(String value) {
            addCriterion("shop_address not like", value, "shopAddress");
            return (Criteria) this;
        }

        public Criteria andShopAddressIn(List<String> values) {
            addCriterion("shop_address in", values, "shopAddress");
            return (Criteria) this;
        }

        public Criteria andShopAddressNotIn(List<String> values) {
            addCriterion("shop_address not in", values, "shopAddress");
            return (Criteria) this;
        }

        public Criteria andShopAddressBetween(String value1, String value2) {
            addCriterion("shop_address between", value1, value2, "shopAddress");
            return (Criteria) this;
        }

        public Criteria andShopAddressNotBetween(String value1, String value2) {
            addCriterion("shop_address not between", value1, value2, "shopAddress");
            return (Criteria) this;
        }

        public Criteria andShopHoldNameIsNull() {
            addCriterion("shop_hold_name is null");
            return (Criteria) this;
        }

        public Criteria andShopHoldNameIsNotNull() {
            addCriterion("shop_hold_name is not null");
            return (Criteria) this;
        }

        public Criteria andShopHoldNameEqualTo(String value) {
            addCriterion("shop_hold_name =", value, "shopHoldName");
            return (Criteria) this;
        }

        public Criteria andShopHoldNameNotEqualTo(String value) {
            addCriterion("shop_hold_name <>", value, "shopHoldName");
            return (Criteria) this;
        }

        public Criteria andShopHoldNameGreaterThan(String value) {
            addCriterion("shop_hold_name >", value, "shopHoldName");
            return (Criteria) this;
        }

        public Criteria andShopHoldNameGreaterThanOrEqualTo(String value) {
            addCriterion("shop_hold_name >=", value, "shopHoldName");
            return (Criteria) this;
        }

        public Criteria andShopHoldNameLessThan(String value) {
            addCriterion("shop_hold_name <", value, "shopHoldName");
            return (Criteria) this;
        }

        public Criteria andShopHoldNameLessThanOrEqualTo(String value) {
            addCriterion("shop_hold_name <=", value, "shopHoldName");
            return (Criteria) this;
        }

        public Criteria andShopHoldNameLike(String value) {
            addCriterion("shop_hold_name like", value, "shopHoldName");
            return (Criteria) this;
        }

        public Criteria andShopHoldNameNotLike(String value) {
            addCriterion("shop_hold_name not like", value, "shopHoldName");
            return (Criteria) this;
        }

        public Criteria andShopHoldNameIn(List<String> values) {
            addCriterion("shop_hold_name in", values, "shopHoldName");
            return (Criteria) this;
        }

        public Criteria andShopHoldNameNotIn(List<String> values) {
            addCriterion("shop_hold_name not in", values, "shopHoldName");
            return (Criteria) this;
        }

        public Criteria andShopHoldNameBetween(String value1, String value2) {
            addCriterion("shop_hold_name between", value1, value2, "shopHoldName");
            return (Criteria) this;
        }

        public Criteria andShopHoldNameNotBetween(String value1, String value2) {
            addCriterion("shop_hold_name not between", value1, value2, "shopHoldName");
            return (Criteria) this;
        }

        public Criteria andShopHoldPhoneIsNull() {
            addCriterion("shop_hold_phone is null");
            return (Criteria) this;
        }

        public Criteria andShopHoldPhoneIsNotNull() {
            addCriterion("shop_hold_phone is not null");
            return (Criteria) this;
        }

        public Criteria andShopHoldPhoneEqualTo(String value) {
            addCriterion("shop_hold_phone =", value, "shopHoldPhone");
            return (Criteria) this;
        }

        public Criteria andShopHoldPhoneNotEqualTo(String value) {
            addCriterion("shop_hold_phone <>", value, "shopHoldPhone");
            return (Criteria) this;
        }

        public Criteria andShopHoldPhoneGreaterThan(String value) {
            addCriterion("shop_hold_phone >", value, "shopHoldPhone");
            return (Criteria) this;
        }

        public Criteria andShopHoldPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("shop_hold_phone >=", value, "shopHoldPhone");
            return (Criteria) this;
        }

        public Criteria andShopHoldPhoneLessThan(String value) {
            addCriterion("shop_hold_phone <", value, "shopHoldPhone");
            return (Criteria) this;
        }

        public Criteria andShopHoldPhoneLessThanOrEqualTo(String value) {
            addCriterion("shop_hold_phone <=", value, "shopHoldPhone");
            return (Criteria) this;
        }

        public Criteria andShopHoldPhoneLike(String value) {
            addCriterion("shop_hold_phone like", value, "shopHoldPhone");
            return (Criteria) this;
        }

        public Criteria andShopHoldPhoneNotLike(String value) {
            addCriterion("shop_hold_phone not like", value, "shopHoldPhone");
            return (Criteria) this;
        }

        public Criteria andShopHoldPhoneIn(List<String> values) {
            addCriterion("shop_hold_phone in", values, "shopHoldPhone");
            return (Criteria) this;
        }

        public Criteria andShopHoldPhoneNotIn(List<String> values) {
            addCriterion("shop_hold_phone not in", values, "shopHoldPhone");
            return (Criteria) this;
        }

        public Criteria andShopHoldPhoneBetween(String value1, String value2) {
            addCriterion("shop_hold_phone between", value1, value2, "shopHoldPhone");
            return (Criteria) this;
        }

        public Criteria andShopHoldPhoneNotBetween(String value1, String value2) {
            addCriterion("shop_hold_phone not between", value1, value2, "shopHoldPhone");
            return (Criteria) this;
        }

        public Criteria andMainbusinessIsNull() {
            addCriterion("mainbusiness is null");
            return (Criteria) this;
        }

        public Criteria andMainbusinessIsNotNull() {
            addCriterion("mainbusiness is not null");
            return (Criteria) this;
        }

        public Criteria andMainbusinessEqualTo(String value) {
            addCriterion("mainbusiness =", value, "mainbusiness");
            return (Criteria) this;
        }

        public Criteria andMainbusinessNotEqualTo(String value) {
            addCriterion("mainbusiness <>", value, "mainbusiness");
            return (Criteria) this;
        }

        public Criteria andMainbusinessGreaterThan(String value) {
            addCriterion("mainbusiness >", value, "mainbusiness");
            return (Criteria) this;
        }

        public Criteria andMainbusinessGreaterThanOrEqualTo(String value) {
            addCriterion("mainbusiness >=", value, "mainbusiness");
            return (Criteria) this;
        }

        public Criteria andMainbusinessLessThan(String value) {
            addCriterion("mainbusiness <", value, "mainbusiness");
            return (Criteria) this;
        }

        public Criteria andMainbusinessLessThanOrEqualTo(String value) {
            addCriterion("mainbusiness <=", value, "mainbusiness");
            return (Criteria) this;
        }

        public Criteria andMainbusinessLike(String value) {
            addCriterion("mainbusiness like", value, "mainbusiness");
            return (Criteria) this;
        }

        public Criteria andMainbusinessNotLike(String value) {
            addCriterion("mainbusiness not like", value, "mainbusiness");
            return (Criteria) this;
        }

        public Criteria andMainbusinessIn(List<String> values) {
            addCriterion("mainbusiness in", values, "mainbusiness");
            return (Criteria) this;
        }

        public Criteria andMainbusinessNotIn(List<String> values) {
            addCriterion("mainbusiness not in", values, "mainbusiness");
            return (Criteria) this;
        }

        public Criteria andMainbusinessBetween(String value1, String value2) {
            addCriterion("mainbusiness between", value1, value2, "mainbusiness");
            return (Criteria) this;
        }

        public Criteria andMainbusinessNotBetween(String value1, String value2) {
            addCriterion("mainbusiness not between", value1, value2, "mainbusiness");
            return (Criteria) this;
        }

        public Criteria andBusinessImagesIsNull() {
            addCriterion("business_images is null");
            return (Criteria) this;
        }

        public Criteria andBusinessImagesIsNotNull() {
            addCriterion("business_images is not null");
            return (Criteria) this;
        }

        public Criteria andBusinessImagesEqualTo(String value) {
            addCriterion("business_images =", value, "businessImages");
            return (Criteria) this;
        }

        public Criteria andBusinessImagesNotEqualTo(String value) {
            addCriterion("business_images <>", value, "businessImages");
            return (Criteria) this;
        }

        public Criteria andBusinessImagesGreaterThan(String value) {
            addCriterion("business_images >", value, "businessImages");
            return (Criteria) this;
        }

        public Criteria andBusinessImagesGreaterThanOrEqualTo(String value) {
            addCriterion("business_images >=", value, "businessImages");
            return (Criteria) this;
        }

        public Criteria andBusinessImagesLessThan(String value) {
            addCriterion("business_images <", value, "businessImages");
            return (Criteria) this;
        }

        public Criteria andBusinessImagesLessThanOrEqualTo(String value) {
            addCriterion("business_images <=", value, "businessImages");
            return (Criteria) this;
        }

        public Criteria andBusinessImagesLike(String value) {
            addCriterion("business_images like", value, "businessImages");
            return (Criteria) this;
        }

        public Criteria andBusinessImagesNotLike(String value) {
            addCriterion("business_images not like", value, "businessImages");
            return (Criteria) this;
        }

        public Criteria andBusinessImagesIn(List<String> values) {
            addCriterion("business_images in", values, "businessImages");
            return (Criteria) this;
        }

        public Criteria andBusinessImagesNotIn(List<String> values) {
            addCriterion("business_images not in", values, "businessImages");
            return (Criteria) this;
        }

        public Criteria andBusinessImagesBetween(String value1, String value2) {
            addCriterion("business_images between", value1, value2, "businessImages");
            return (Criteria) this;
        }

        public Criteria andBusinessImagesNotBetween(String value1, String value2) {
            addCriterion("business_images not between", value1, value2, "businessImages");
            return (Criteria) this;
        }

        public Criteria andIdentityNumberIsNull() {
            addCriterion("identity_number is null");
            return (Criteria) this;
        }

        public Criteria andIdentityNumberIsNotNull() {
            addCriterion("identity_number is not null");
            return (Criteria) this;
        }

        public Criteria andIdentityNumberEqualTo(String value) {
            addCriterion("identity_number =", value, "identityNumber");
            return (Criteria) this;
        }

        public Criteria andIdentityNumberNotEqualTo(String value) {
            addCriterion("identity_number <>", value, "identityNumber");
            return (Criteria) this;
        }

        public Criteria andIdentityNumberGreaterThan(String value) {
            addCriterion("identity_number >", value, "identityNumber");
            return (Criteria) this;
        }

        public Criteria andIdentityNumberGreaterThanOrEqualTo(String value) {
            addCriterion("identity_number >=", value, "identityNumber");
            return (Criteria) this;
        }

        public Criteria andIdentityNumberLessThan(String value) {
            addCriterion("identity_number <", value, "identityNumber");
            return (Criteria) this;
        }

        public Criteria andIdentityNumberLessThanOrEqualTo(String value) {
            addCriterion("identity_number <=", value, "identityNumber");
            return (Criteria) this;
        }

        public Criteria andIdentityNumberLike(String value) {
            addCriterion("identity_number like", value, "identityNumber");
            return (Criteria) this;
        }

        public Criteria andIdentityNumberNotLike(String value) {
            addCriterion("identity_number not like", value, "identityNumber");
            return (Criteria) this;
        }

        public Criteria andIdentityNumberIn(List<String> values) {
            addCriterion("identity_number in", values, "identityNumber");
            return (Criteria) this;
        }

        public Criteria andIdentityNumberNotIn(List<String> values) {
            addCriterion("identity_number not in", values, "identityNumber");
            return (Criteria) this;
        }

        public Criteria andIdentityNumberBetween(String value1, String value2) {
            addCriterion("identity_number between", value1, value2, "identityNumber");
            return (Criteria) this;
        }

        public Criteria andIdentityNumberNotBetween(String value1, String value2) {
            addCriterion("identity_number not between", value1, value2, "identityNumber");
            return (Criteria) this;
        }

        public Criteria andIdentityImagesIsNull() {
            addCriterion("identity_images is null");
            return (Criteria) this;
        }

        public Criteria andIdentityImagesIsNotNull() {
            addCriterion("identity_images is not null");
            return (Criteria) this;
        }

        public Criteria andIdentityImagesEqualTo(String value) {
            addCriterion("identity_images =", value, "identityImages");
            return (Criteria) this;
        }

        public Criteria andIdentityImagesNotEqualTo(String value) {
            addCriterion("identity_images <>", value, "identityImages");
            return (Criteria) this;
        }

        public Criteria andIdentityImagesGreaterThan(String value) {
            addCriterion("identity_images >", value, "identityImages");
            return (Criteria) this;
        }

        public Criteria andIdentityImagesGreaterThanOrEqualTo(String value) {
            addCriterion("identity_images >=", value, "identityImages");
            return (Criteria) this;
        }

        public Criteria andIdentityImagesLessThan(String value) {
            addCriterion("identity_images <", value, "identityImages");
            return (Criteria) this;
        }

        public Criteria andIdentityImagesLessThanOrEqualTo(String value) {
            addCriterion("identity_images <=", value, "identityImages");
            return (Criteria) this;
        }

        public Criteria andIdentityImagesLike(String value) {
            addCriterion("identity_images like", value, "identityImages");
            return (Criteria) this;
        }

        public Criteria andIdentityImagesNotLike(String value) {
            addCriterion("identity_images not like", value, "identityImages");
            return (Criteria) this;
        }

        public Criteria andIdentityImagesIn(List<String> values) {
            addCriterion("identity_images in", values, "identityImages");
            return (Criteria) this;
        }

        public Criteria andIdentityImagesNotIn(List<String> values) {
            addCriterion("identity_images not in", values, "identityImages");
            return (Criteria) this;
        }

        public Criteria andIdentityImagesBetween(String value1, String value2) {
            addCriterion("identity_images between", value1, value2, "identityImages");
            return (Criteria) this;
        }

        public Criteria andIdentityImagesNotBetween(String value1, String value2) {
            addCriterion("identity_images not between", value1, value2, "identityImages");
            return (Criteria) this;
        }

        public Criteria andSuppliesAddressIsNull() {
            addCriterion("supplies_address is null");
            return (Criteria) this;
        }

        public Criteria andSuppliesAddressIsNotNull() {
            addCriterion("supplies_address is not null");
            return (Criteria) this;
        }

        public Criteria andSuppliesAddressEqualTo(String value) {
            addCriterion("supplies_address =", value, "suppliesAddress");
            return (Criteria) this;
        }

        public Criteria andSuppliesAddressNotEqualTo(String value) {
            addCriterion("supplies_address <>", value, "suppliesAddress");
            return (Criteria) this;
        }

        public Criteria andSuppliesAddressGreaterThan(String value) {
            addCriterion("supplies_address >", value, "suppliesAddress");
            return (Criteria) this;
        }

        public Criteria andSuppliesAddressGreaterThanOrEqualTo(String value) {
            addCriterion("supplies_address >=", value, "suppliesAddress");
            return (Criteria) this;
        }

        public Criteria andSuppliesAddressLessThan(String value) {
            addCriterion("supplies_address <", value, "suppliesAddress");
            return (Criteria) this;
        }

        public Criteria andSuppliesAddressLessThanOrEqualTo(String value) {
            addCriterion("supplies_address <=", value, "suppliesAddress");
            return (Criteria) this;
        }

        public Criteria andSuppliesAddressLike(String value) {
            addCriterion("supplies_address like", value, "suppliesAddress");
            return (Criteria) this;
        }

        public Criteria andSuppliesAddressNotLike(String value) {
            addCriterion("supplies_address not like", value, "suppliesAddress");
            return (Criteria) this;
        }

        public Criteria andSuppliesAddressIn(List<String> values) {
            addCriterion("supplies_address in", values, "suppliesAddress");
            return (Criteria) this;
        }

        public Criteria andSuppliesAddressNotIn(List<String> values) {
            addCriterion("supplies_address not in", values, "suppliesAddress");
            return (Criteria) this;
        }

        public Criteria andSuppliesAddressBetween(String value1, String value2) {
            addCriterion("supplies_address between", value1, value2, "suppliesAddress");
            return (Criteria) this;
        }

        public Criteria andSuppliesAddressNotBetween(String value1, String value2) {
            addCriterion("supplies_address not between", value1, value2, "suppliesAddress");
            return (Criteria) this;
        }

        public Criteria andSuppliesPatternIsNull() {
            addCriterion("supplies_pattern is null");
            return (Criteria) this;
        }

        public Criteria andSuppliesPatternIsNotNull() {
            addCriterion("supplies_pattern is not null");
            return (Criteria) this;
        }

        public Criteria andSuppliesPatternEqualTo(String value) {
            addCriterion("supplies_pattern =", value, "suppliesPattern");
            return (Criteria) this;
        }

        public Criteria andSuppliesPatternNotEqualTo(String value) {
            addCriterion("supplies_pattern <>", value, "suppliesPattern");
            return (Criteria) this;
        }

        public Criteria andSuppliesPatternGreaterThan(String value) {
            addCriterion("supplies_pattern >", value, "suppliesPattern");
            return (Criteria) this;
        }

        public Criteria andSuppliesPatternGreaterThanOrEqualTo(String value) {
            addCriterion("supplies_pattern >=", value, "suppliesPattern");
            return (Criteria) this;
        }

        public Criteria andSuppliesPatternLessThan(String value) {
            addCriterion("supplies_pattern <", value, "suppliesPattern");
            return (Criteria) this;
        }

        public Criteria andSuppliesPatternLessThanOrEqualTo(String value) {
            addCriterion("supplies_pattern <=", value, "suppliesPattern");
            return (Criteria) this;
        }

        public Criteria andSuppliesPatternLike(String value) {
            addCriterion("supplies_pattern like", value, "suppliesPattern");
            return (Criteria) this;
        }

        public Criteria andSuppliesPatternNotLike(String value) {
            addCriterion("supplies_pattern not like", value, "suppliesPattern");
            return (Criteria) this;
        }

        public Criteria andSuppliesPatternIn(List<String> values) {
            addCriterion("supplies_pattern in", values, "suppliesPattern");
            return (Criteria) this;
        }

        public Criteria andSuppliesPatternNotIn(List<String> values) {
            addCriterion("supplies_pattern not in", values, "suppliesPattern");
            return (Criteria) this;
        }

        public Criteria andSuppliesPatternBetween(String value1, String value2) {
            addCriterion("supplies_pattern between", value1, value2, "suppliesPattern");
            return (Criteria) this;
        }

        public Criteria andSuppliesPatternNotBetween(String value1, String value2) {
            addCriterion("supplies_pattern not between", value1, value2, "suppliesPattern");
            return (Criteria) this;
        }

        public Criteria andSuppliesDateIsNull() {
            addCriterion("supplies_date is null");
            return (Criteria) this;
        }

        public Criteria andSuppliesDateIsNotNull() {
            addCriterion("supplies_date is not null");
            return (Criteria) this;
        }

        public Criteria andSuppliesDateEqualTo(Date value) {
            addCriterion("supplies_date =", value, "suppliesDate");
            return (Criteria) this;
        }

        public Criteria andSuppliesDateNotEqualTo(Date value) {
            addCriterion("supplies_date <>", value, "suppliesDate");
            return (Criteria) this;
        }

        public Criteria andSuppliesDateGreaterThan(Date value) {
            addCriterion("supplies_date >", value, "suppliesDate");
            return (Criteria) this;
        }

        public Criteria andSuppliesDateGreaterThanOrEqualTo(Date value) {
            addCriterion("supplies_date >=", value, "suppliesDate");
            return (Criteria) this;
        }

        public Criteria andSuppliesDateLessThan(Date value) {
            addCriterion("supplies_date <", value, "suppliesDate");
            return (Criteria) this;
        }

        public Criteria andSuppliesDateLessThanOrEqualTo(Date value) {
            addCriterion("supplies_date <=", value, "suppliesDate");
            return (Criteria) this;
        }

        public Criteria andSuppliesDateIn(List<Date> values) {
            addCriterion("supplies_date in", values, "suppliesDate");
            return (Criteria) this;
        }

        public Criteria andSuppliesDateNotIn(List<Date> values) {
            addCriterion("supplies_date not in", values, "suppliesDate");
            return (Criteria) this;
        }

        public Criteria andSuppliesDateBetween(Date value1, Date value2) {
            addCriterion("supplies_date between", value1, value2, "suppliesDate");
            return (Criteria) this;
        }

        public Criteria andSuppliesDateNotBetween(Date value1, Date value2) {
            addCriterion("supplies_date not between", value1, value2, "suppliesDate");
            return (Criteria) this;
        }

        public Criteria andTenantPayPwdIsNull() {
            addCriterion("tenant_pay_pwd is null");
            return (Criteria) this;
        }

        public Criteria andTenantPayPwdIsNotNull() {
            addCriterion("tenant_pay_pwd is not null");
            return (Criteria) this;
        }

        public Criteria andTenantPayPwdEqualTo(String value) {
            addCriterion("tenant_pay_pwd =", value, "tenantPayPwd");
            return (Criteria) this;
        }

        public Criteria andTenantPayPwdNotEqualTo(String value) {
            addCriterion("tenant_pay_pwd <>", value, "tenantPayPwd");
            return (Criteria) this;
        }

        public Criteria andTenantPayPwdGreaterThan(String value) {
            addCriterion("tenant_pay_pwd >", value, "tenantPayPwd");
            return (Criteria) this;
        }

        public Criteria andTenantPayPwdGreaterThanOrEqualTo(String value) {
            addCriterion("tenant_pay_pwd >=", value, "tenantPayPwd");
            return (Criteria) this;
        }

        public Criteria andTenantPayPwdLessThan(String value) {
            addCriterion("tenant_pay_pwd <", value, "tenantPayPwd");
            return (Criteria) this;
        }

        public Criteria andTenantPayPwdLessThanOrEqualTo(String value) {
            addCriterion("tenant_pay_pwd <=", value, "tenantPayPwd");
            return (Criteria) this;
        }

        public Criteria andTenantPayPwdLike(String value) {
            addCriterion("tenant_pay_pwd like", value, "tenantPayPwd");
            return (Criteria) this;
        }

        public Criteria andTenantPayPwdNotLike(String value) {
            addCriterion("tenant_pay_pwd not like", value, "tenantPayPwd");
            return (Criteria) this;
        }

        public Criteria andTenantPayPwdIn(List<String> values) {
            addCriterion("tenant_pay_pwd in", values, "tenantPayPwd");
            return (Criteria) this;
        }

        public Criteria andTenantPayPwdNotIn(List<String> values) {
            addCriterion("tenant_pay_pwd not in", values, "tenantPayPwd");
            return (Criteria) this;
        }

        public Criteria andTenantPayPwdBetween(String value1, String value2) {
            addCriterion("tenant_pay_pwd between", value1, value2, "tenantPayPwd");
            return (Criteria) this;
        }

        public Criteria andTenantPayPwdNotBetween(String value1, String value2) {
            addCriterion("tenant_pay_pwd not between", value1, value2, "tenantPayPwd");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_user
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_user
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}