package com.xuyang.service;

import com.xuyang.model.Tworldtype;

public interface TworldTypeService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_worldtype
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer wotId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_worldtype
     *
     * @mbg.generated
     */
    int insert(Tworldtype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_worldtype
     *
     * @mbg.generated
     */
    int insertSelective(Tworldtype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_worldtype
     *
     * @mbg.generated
     */
    Tworldtype selectByPrimaryKey(Integer wotId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_worldtype
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Tworldtype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_worldtype
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Tworldtype record);
}
